---
title: "composition_analysis"
output: html_document
date: "2024-10-24"
author: "David Zemmour"
editor_options: 
  chunk_output_type: console
---

**Initialize: load libraries and custom functions**

```{bash}
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=jfkfloor2 --qos=jfkfloor2 --nodes=1 
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=beagle3-bigmem --nodes=1 
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=zemmour-hm --qos=zemmour --nodes=1 
sinteractive --time=03:00:00 --account=pi-zemmour --partition=caslake --nodes=1 --mem=96GB

module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13
#source activate /project/zemmour/david/envs/scvi_20240315
source activate /project/zemmour/david/envs/r443
module load openblas/0.3.13

cd /project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/CD8
R
```


```{r}
# setwd("~/google_drive_uchicago/ImmgenT/analysis/data_integration/IGT1_96")
libs = c("Seurat","lme4", "emmeans", "lmerTest", "tidyr", "ggplot2", "dplyr", "RColorBrewer", "pals", "scales", "reshape2", "pheatmap", "scattermore", "limma", "ggbeeswarm") 
sapply(libs, function(x) suppressMessages(suppressWarnings(library(x, character.only = TRUE, quietly = T, warn.conflicts  = F))))
source("/project/jfkfloor2/zemmourlab/david/immgent/immgent_integration_git/custom_functions_david.R")

ColorRamp = rev(colorRampPalette(brewer.pal(n = 7,name = "RdYlBu"))(100))
ColorRamp = rev(colorRampPalette(c('red','white','blue'))(20))
ColorRamp = rev(rainbow(10, end = 4/6))
ColorRamp = rev(viridis(100))
ColorRamp = brewer.pal(9, "Blues")

#mycol = c("black","blue","red","darkgreen", "orange","purple", "cyan", "greenyellow",    "salmon", "magenta","pink", "tan", "brown") # c("magenta", "red",  "darkgreen", "cyan", "blue", "blue", "blue", "black", "blue", "blue", "blue", "blue", "orange")

n = 70
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
mypal1 = unique(unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals))))
mypal1 = mypal1[-4]

library("pals")
parade = function(n) { return(Seurat::DiscretePalette(n, palette = "parade", shuffle = F)) }

length(glasbey())
length(polychrome())
mypal = c(glasbey(), polychrome(), mypal1)
names(mypal) = NULL

mypal_organ = setNames(mypal, unique(so$organ_simplified))
mypal_organ["other"] = "grey"
mypal_organ = mypal_organ[!is.na(names(mypal_organ))]
mypal_organ = setNames(mypal, unique(mdata_orig$organ_simplified))
mypal_organ["other"] = "grey"
mypal_organ = mypal_organ[!is.na(names(mypal_organ))]

mypal_level1 = setNames(mypal, unique(so$annotation_level1))
mypal_level1 = mypal_level1[!is.na(names(mypal_level1))]

mypal_level2 = setNames(mypal, unique(so$annotation_level2))
mypal_level2 = mypal_level2[!is.na(names(mypal_level2))]

mypal_condition_broad = setNames(mypal, unique(so$condition_broad))
mypal_condition_broad = mypal_condition_broad[!is.na(names(mypal_condition_broad))]

mypal_condition_broad = setNames(mypal, unique(mdata_orig$condition_broad))
mypal_condition_broad = mypal_condition_broad[!is.na(names(mypal_condition_broad))]
mypal_condition_broad["healthy"] = "black"
mypal_condition_broad["allergy"] = mypal[60]

mypal_condition_detailed_simplified = setNames(mypal, unique(so$condition_detailed_simplified))
mypal_condition_detailed_simplified = mypal_condition_detailed_simplified[!is.na(names(mypal_condition_detailed_simplified))]

mypal_igt = setNames(mypal, unique(so$IGT))
mypal_igt = mypal_igt[!is.na(names(mypal_igt))]
```

**Most up-to-date data**

```{r}
so_orig = readRDS("igt1_96_withtotalvi20250317_clean.Rds")
so = so[,so$annotation_level1 == "CD8"]
so$Ag_spe[is.na(so$Ag_spe)] = "poly"

prefix = "CD8"

so@meta.data %>% select(IGT, infection_agent) %>% unique()
so@meta.data %>% select(IGT, tumor, Ag_spe) %>% unique()

```

LCMV arm
```{r}
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level2", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal) + theme_void() + NoLegend() 

ia = "LCMV armstrong"
igts = c("IGT36", "IGT38", "IGT40")
orgs = unique(so$organ_simplified)
as = c("P14", "poly")

ip = c("acute")
pdf(sprintf("%s/MDE_LCMVarm_acutephase_20250402.pdf", prefix), 5, 5, useDingbats = F)
for (o in orgs) {
    for (a in as) {
        ch = colnames(so)[so$infection_agent %in% ia & so$IGT %in% igts & so$infection_phase %in% ip & so$organ_simplified %in% o & so$Ag_spe %in% a]
        if (length(ch) != 0 ) {
            print(sprintf("%s %s %s %s", ia, ip, o, a))
            print(length(ch))
            MyDimPlotHighlight(so, umap_to_plot = "mde_incremental", cells_to_highlight = ch, highlight_column_name = "annotation_level2", highlight_size = 0.5, highlight_alpha = 0.5, pixels = c(512, 512), mycols = mypal_level2, print_plot1 = T, print_plot2 = T, labelclusters = F, title = sprintf("%s %s %s %s", ia, ip, o, a) )
            rm(ch)
        }
    }
}
dev.off()

ip = c("cleared")
pdf(sprintf("%s/MDE_LCMVarm_latephase_20250402.pdf", prefix), 5, 5, useDingbats = F)
for (o in orgs) {
    for (a in as) {
        ch = colnames(so)[so$infection_agent %in% ia & so$IGT %in% igts & so$infection_phase %in% ip & so$organ_simplified %in% o & so$Ag_spe %in% a]
        if (length(ch) != 0 ) {
            print(sprintf("%s %s %s %s", ia, ip, o, a))
            print(length(ch))
            MyDimPlotHighlight(so, umap_to_plot = "mde_incremental", cells_to_highlight = ch, highlight_column_name = "annotation_level2", highlight_size = 0.5, highlight_alpha = 0.5, pixels = c(512, 512), mycols = mypal_level2, print_plot1 = T, print_plot2 = T, labelclusters = F, title = sprintf("%s %s %s %s", ia, ip, o, a) )
            rm(ch)
        }
    }
}


dev.off()

pdf(sprintf("%s/MDE_IGT36_38_40_48_spleen_standard.pdf", prefix), 5, 5, useDingbats = F)
ch = colnames(so)[so$IGT %in% c("IGT36", "IGT38", "IGT40", "IGT48") & so$spleen_standard == T]
MyDimPlotHighlight(so, umap_to_plot = "mde_incremental", cells_to_highlight = ch, highlight_column_name = "annotation_level2", highlight_size = 0.5, highlight_alpha = 0.5, pixels = c(512, 512), mycols = mypal_level2, print_plot1 = T, print_plot2 = T, labelclusters = F, title = "spleen standard" )
dev.off()

```

B16
```{r}
# igts = c("IGT35")
spls = unique(so$sample_type[so$IGT == "IGT35"])
as = c("P14", "poly")

pdf(sprintf("%s/MDE_B16.gp33_20250402.pdf", prefix), 5, 5, useDingbats = F)
for (s in spls) {
    for (a in as) {
        ch = colnames(so)[so$sample_type %in% s & so$Ag_spe %in% a ] #
        if (length(ch) != 0 ) {
            print(sprintf("%s %s", s, a))
            print(length(ch))
            MyDimPlotHighlight(so, umap_to_plot = "mde_incremental", cells_to_highlight = ch, highlight_column_name = "annotation_level2", highlight_size = 0.5, highlight_alpha = 0.5, pixels = c(512, 512), mycols = mypal_level2, print_plot1 = T, print_plot2 = T, labelclusters = F, title = sprintf("%s %s", s,  a) )
            rm(ch)
        }
    }
}
dev.off()


```

KP
```{r}
# igts = c("IGT35")
spls = unique(so$sample_type[so$IGT %in% c("IGT95", "IGT96")])
as = c("OT1", "poly")

pdf(sprintf("%s/MDE_KPzSIIN_20250402.pdf", prefix), 5, 5, useDingbats = F)
for (s in spls) {
    for (a in as) {
        ch = colnames(so)[so$sample_type %in% s & so$Ag_spe %in% a ] #
        if (length(ch) != 0 ) {
            print(sprintf("%s %s", s, a))
            print(length(ch))
            MyDimPlotHighlight(so, umap_to_plot = "mde_incremental", cells_to_highlight = ch, highlight_column_name = "annotation_level2", highlight_size = 0.5, highlight_alpha = 0.5, pixels = c(512, 512), mycols = mypal_level2, print_plot1 = T, print_plot2 = T, labelclusters = F, title = sprintf("%s %s", s,  a) )
            rm(ch)
        }
    }
}
dev.off()
```

KP
```{r}
# igts = c("IGT35")
spls = unique(so$sample_type[so$IGT %in% c("IGT64", "IGT65")])
as = c("OT1", "poly")

pdf(sprintf("%s/MDE_PDAC_20250402.pdf", prefix), 5, 5, useDingbats = F)
for (s in spls) {
    for (a in as) {
        ch = colnames(so)[so$sample_type %in% s & so$Ag_spe %in% a ] #
        if (length(ch) != 0 ) {
            print(sprintf("%s %s", s, a))
            print(length(ch))
            MyDimPlotHighlight(so, umap_to_plot = "mde_incremental", cells_to_highlight = ch, highlight_column_name = "annotation_level2", highlight_size = 0.5, highlight_alpha = 0.5, pixels = c(512, 512), mycols = mypal_level2, print_plot1 = T, print_plot2 = T, labelclusters = F, title = sprintf("%s %s", s,  a) )
            rm(ch)
        }
    }
}
dev.off()


```

GBM
```{r}
# igts = c("IGT35")
spls = unique(so$sample_type[so$IGT %in% c("IGT69")])
as = c("OT1", "poly")

pdf(sprintf("%s/MDE_GBM_20250402.pdf", prefix), 5, 5, useDingbats = F)
for (s in spls) {
    for (a in as) {
        ch = colnames(so)[so$sample_type %in% s & so$Ag_spe %in% a ] #
        if (length(ch) != 0 ) {
            print(sprintf("%s %s", s, a))
            print(length(ch))
            MyDimPlotHighlight(so, umap_to_plot = "mde_incremental", cells_to_highlight = ch, highlight_column_name = "annotation_level2", highlight_size = 0.5, highlight_alpha = 0.5, pixels = c(512, 512), mycols = mypal_level2, print_plot1 = T, print_plot2 = T, labelclusters = F, title = sprintf("%s %s", s,  a) )
            rm(ch)
        }
    }
}
dev.off()


```

**FCFC plots for giovanni**
```{r}
source('/Users/david/Library/CloudStorage/GoogleDrive-david.puyraimond@gmail.com/My Drive/ImmgenT/analysis/immgent_integration_git/custom_functions_david.R')

tt_list = readRDS('/Users/david/Library/CloudStorage/GoogleDrive-zemmour@uchicago.edu/My Drive/ImmgenT/analysis/data_integration/IGT1_96/CD8/DGE_limma/20250109/ttlist_OneVsAll.Rds')

names(tt_list)


# Create the vplot dataframe with fold changes
vplot = data.frame(fc1 = exp(tt_list$CD8_cl10_vs_All$logFC), fc2 = exp(tt_list$CD8_cl11_vs_All$logFC), SYMBOL = tt_list$CD8_cl10_vs_All$SYMBOL)

# Identify genes with large fold changes (>2)
genes_to_plot = abs(tt_list$CD8_cl10_vs_All$logFC) > 0.69 | abs(tt_list$CD8_cl11_vs_All$logFC) > 0.69
# genes_to_label = vplot[genes_to_plot, ]
genes_to_label = vplot$SYMBOL[genes_to_plot]

# Create the plot
FCFCplot(vplot, 
         xlab = "FC for CD8_cl10", 
         ylab = "FC for CD8_cl11", 
         main = "Fold Change vs Fold Change", 
         genes_to_label = genes_to_label)

FCFCplot(vplot, 
         xlab = "FC for CD8_cl10", 
         ylab = "FC for CD8_cl11", 
         main = "Fold Change vs Fold Change", 
         genes_to_label = NULL)

vplot = data.frame(fc1 = exp(tt_list$CD8_cl10_vs_All$logFC), fc2 = exp(tt_list$CD8_cl7_vs_All$logFC), SYMBOL = tt_list$CD8_cl10_vs_All$SYMBOL)
# Identify genes with large fold changes (>2)
genes_to_plot = abs(tt_list$CD8_cl10_vs_All$logFC) > 0.69 | abs(tt_list$CD8_cl7_vs_All$logFC) > 0.69
genes_to_label = vplot[genes_to_plot, ]
# Create the plot
FCFCplot(vplot, 
         xlab = "FC for CD8_cl10", 
         ylab = "FC for CD8_cl7", 
         main = "Fold Change vs Fold Change", 
         printgeomtext = T, 
         genes_to_label = genes_to_label)



```















