---
title: "clustering_abT_DN"
output: html_document
date: "2024-12-01"
editor_options: 
  chunk_output_type: console
---

**Start interactive session on Midway3**
```{bash}
ssh -Y zemmour@midway3.rcc.uchicago.edu
sinfo -s
screen -S david
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=jfkfloor2 --qos=jfkfloor2 --nodes=1 
sinteractive --time=12:00:00 --account=pi-zemmour --partition=caslake --nodes=1 --mem=128GB
sinteractive --time=12:00:00 --account=pi-zemmour --partition=gpu --gres=gpu:1 --mem=152GB
cd $LABHOME

module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13

#sinteractive --time=1:00:00 -p gpu --gres=gpu:1 --account=pi-zemmour 

#source activate /project/jfkfloor2/zemmourlab/david/envs/scvi
source activate /project/zemmour/david/envs/scvi_20240315
module load openblas/0.3.13 #load again or error

cd /project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DN
#cd ~/google_drive/ImmgenT/analysis/data_integration/IGT1_56/Treg

R
#options(max.print=1000)
#options(Seurat.object.assay.version = 'v5')
```

**Initialize: load libraries and custom functions**

```{r}
options(max.print=1000)
setwd("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DN")
source("/project/jfkfloor2/zemmourlab/david/immgent/immgent_integration_git/custom_functions_david.R")
""
libs = c("fgsea","fastTopics", "flashier", "Matrix", "Seurat","BPCells", "ggplot2", "dplyr", "reshape2", "ggrastr", "RColorBrewer", "pals", "scales", "pheatmap", "scattermore") 
#libs = c("matrixStats", "gplots","ggplot2", "reshape2", "scales", "gridExtra", "dplyr", "RColorBrewer", "grid", "Rtsne", "limma",   "RColorBrewer", "pheatmap", "Seurat",  "ggrastr", "ggbeeswarm") #pwr, preprocessCore, "readxl", vegan", "genefilter" "scde" "cellrangerRkit", "Rsamtools", "GenomicRanges", "GenomicAlignments", "VGAM", "WGCNA",rafalib, ‘UsingR’,MAST "ggrastr",
sapply(libs, function(x) suppressMessages(suppressWarnings(library(x, character.only = TRUE, quietly = T, warn.conflicts  = F))))


#Gradients
library(RColorBrewer)
ColorRamp = rev(colorRampPalette(brewer.pal(n = 7,name = "RdYlBu"))(100))
ColorRamp = rev(colorRampPalette(c('red','white','blue'))(20))
ColorRamp = rev(rainbow(10, end = 4/6))
library(viridis)
ColorRamp = rev(viridis(100))
ColorRamp = rev(cividis(100))
#image(1:100, 1, as.matrix(1:100), col = ColorRamp, main = "Color Palette", xaxt = 'n', yaxt = 'n', xlab = "", ylab = "")

#mycol = c("black","blue","red","darkgreen", "orange","purple", "cyan", "greenyellow",    "salmon", "magenta","pink", "tan", "brown") # c("magenta", "red",  "darkgreen", "cyan", "blue", "blue", "blue", "black", "blue", "blue", "blue", "blue", "orange")

#Large Color palette
library("pals")
n = 70
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
mypal1 = unique(unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals))))
mypal1 = mypal1[-4]
mypal = c(glasbey(), polychrome(), mypal1)
names(mypal) = NULL
#pal.bands(mypal, main="Colormap suggestions")

#parade = function(n) { return(Seurat::DiscretePalette(n, palette = "parade", shuffle = F)) }


```

**clustering V3 20241201**
 cluster_adjustments.Rmd: sbatch $SCRIPT_DIR/run_totalvi_wrapper_20241201_abT_DN_rmIGTsample.sh

```{r}
prefix = "totalvi_20241201_abT_DN_rmIGTsample"
umap_to_plot = "mde_totalvi_20241201_abT_DN_rmIGTsample"

so_orig = readRDS("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/igt1_96_withtotalvi20241201.Rds")
setwd("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DN")
so = so_orig[,so_orig$annotation_level1 == "abT_DN"]

dir_with_file = "/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DN/totalvi_20241201_abT_DN_rmIGTsample"
so = AddLatentData(so, latent_file = sprintf("%s/latent.csv",dir_with_file), prefix = "totalvi_20241201_abT_DN_rmIGTsample", calculate_umap = F)
so = AddLatentData(so, latent_file = sprintf("%s/mde2.csv",dir_with_file), prefix = "mde_totalvi_20241201_abT_DN_rmIGTsample", calculate_umap = F)


pdf(sprintf("%s/MDE_clusters.pdf", prefix), 20, 20, useDingbats = F)
DimPlot(so, reduction = umap_to_plot, group.by = "annotation_level1", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal)
DimPlot(so, reduction = umap_to_plot, group.by = "annotation_level2", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal)
MyDimPlotHighlight(seurat_object = so, umap_to_plot = umap_to_plot, cells_to_highlight = names(which(so$nonconv_tcr_recog == T)), highlight_column = "nonconv_tcr_recog", pixels = c(512, 512), mycols = "red")
MyDimPlotHighlight(seurat_object = so, umap_to_plot = umap_to_plot, cells_to_highlight = names(which(so$iNKT == T)), highlight_column = "iNKT", pixels = c(512, 512), mycols = "red")
MyDimPlotHighlight(seurat_object = so, umap_to_plot = umap_to_plot, cells_to_highlight = names(which(so$MAIT == T)), highlight_column = "MAIT", pixels = c(512, 512), mycols = "red")
dev.off()

saveRDS(so, file = "igt1_96_abT_DN_20241201.Rds")

so = readRDS("igt1_96_abT_DN_20241201.Rds")
outliers = names(which(so[[umap_to_plot]]@cell.embeddings[,2] >5))
write.table(outliers, file = "outliers_abT_DN.csv", sep = ",", quote = F, row.names = F, col.names = F)

so$outliers_abT_DN = colnames(so) %in% outliers
saveRDS(so, file = "igt1_96_abT_DN_20241201.Rds")

so = so[,!colnames(so) %in% outliers]

pdf(sprintf("%s/MDE_clusters_nooutliers.pdf", prefix), 20, 20, useDingbats = F)
DimPlot(so, reduction = umap_to_plot, group.by = "annotation_level1", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal)
DimPlot(so, reduction = umap_to_plot, group.by = "annotation_level2", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal)
MyDimPlotHighlight(seurat_object = so, umap_to_plot = umap_to_plot, cells_to_highlight = names(which(so$nonconv_tcr_recog == T)), highlight_column = "nonconv_tcr_recog", pixels = c(512, 512), mycols = "red")
MyDimPlotHighlight(seurat_object = so, umap_to_plot = umap_to_plot, cells_to_highlight = names(which(so$iNKT == T)), highlight_column = "iNKT", pixels = c(512, 512), mycols = "red")
MyDimPlotHighlight(seurat_object = so, umap_to_plot = umap_to_plot, cells_to_highlight = names(which(so$MAIT == T)), highlight_column = "MAIT", pixels = c(512, 512), mycols = "red")
dev.off()

```

**clustering V4 20241202**
cluster_adjustments.Rmd: sbatch $SCRIPT_DIR/run_totalvi_wrapper_20241202_abT_CD8aa_rmIGTsample.sh
--> igt1_96_abT_CD8aa_20241202.Rds


```

