---
title: "clustering_abT_DP"
output: html_document
date: "2025-01-09"
editor_options: 
  chunk_output_type: console
---

**Start interactive session on Midway3**
```{bash}
ssh -Y zemmour@midway3.rcc.uchicago.edu
sinfo -s
screen -S david
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=jfkfloor2 --qos=jfkfloor2 --nodes=1 
sinteractive --time=12:00:00 --account=pi-zemmour --partition=caslake --nodes=1 --mem=128GB
sinteractive --time=12:00:00 --account=pi-zemmour --partition=beagle3 --gres=gpu:1 --mem=128GB
cd $LABHOME

module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13

#sinteractive --time=1:00:00 -p gpu --gres=gpu:1 --account=pi-zemmour 

#source activate /project/jfkfloor2/zemmourlab/david/envs/scvi
source activate /project/zemmour/david/envs/scvi_20240315
module load openblas/0.3.13 #load again or error

module load python
source activate /project/zemmour/david/envs/scvi120_20241008 #for scvi 1.2.0

cd /project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DP
#cd ~/google_drive/ImmgenT/analysis/data_integration/IGT1_56/Treg


R
#options(max.print=1000)
#options(Seurat.object.assay.version = 'v5')
```

**Initialize: load libraries and custom functions**

```{r}
options(max.print=1000)
setwd("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DP")
source("/project/jfkfloor2/zemmourlab/david/immgent/immgent_integration_git/custom_functions_david.R")

libs = c("fgsea","fastTopics", "flashier", "Matrix", "Seurat","BPCells", "ggplot2", "dplyr", "reshape2", "ggrastr", "RColorBrewer", "pals", "scales", "pheatmap", "scattermore") 
#libs = c("matrixStats", "gplots","ggplot2", "reshape2", "scales", "gridExtra", "dplyr", "RColorBrewer", "grid", "Rtsne", "limma",   "RColorBrewer", "pheatmap", "Seurat",  "ggrastr", "ggbeeswarm") #pwr, preprocessCore, "readxl", vegan", "genefilter" "scde" "cellrangerRkit", "Rsamtools", "GenomicRanges", "GenomicAlignments", "VGAM", "WGCNA",rafalib, ‘UsingR’,MAST "ggrastr",
sapply(libs, function(x) suppressMessages(suppressWarnings(library(x, character.only = TRUE, quietly = T, warn.conflicts  = F))))


#Gradients
library(RColorBrewer)
ColorRamp = rev(colorRampPalette(brewer.pal(n = 7,name = "RdYlBu"))(100))
ColorRamp = rev(colorRampPalette(c('red','white','blue'))(20))
ColorRamp = rev(rainbow(10, end = 4/6))
library(viridis)
ColorRamp = rev(viridis(100))
ColorRamp = rev(cividis(100))
#image(1:100, 1, as.matrix(1:100), col = ColorRamp, main = "Color Palette", xaxt = 'n', yaxt = 'n', xlab = "", ylab = "")

#mycol = c("black","blue","red","darkgreen", "orange","purple", "cyan", "greenyellow",    "salmon", "magenta","pink", "tan", "brown") # c("magenta", "red",  "darkgreen", "cyan", "blue", "blue", "blue", "black", "blue", "blue", "blue", "blue", "orange")

#Large Color palette
library("pals")
n = 70
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
mypal1 = unique(unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals))))
mypal1 = mypal1[-4]
mypal = c(glasbey(), polychrome(), mypal1)
names(mypal) = NULL
#pal.bands(mypal, main="Colormap suggestions")

#parade = function(n) { return(Seurat::DiscretePalette(n, palette = "parade", shuffle = F)) }


```

**Calculate MDE**
```{python}

import warnings; warnings.simplefilter('ignore')
import argparse

working_dir='/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DP/'
path_to_mudata='/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/export_data/igt1_96_20250109_abT_DP.h5mu'
prefix='20250109_abT_DP'
totalvi_integrated_file='/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/totalvi_20241008_rmIGTsample/latent_abT_DP.csv'
annotation = '/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/annotation_table_20250109.csv'

print("Importing libraries")
import warnings; warnings.simplefilter('ignore')
import scvi
import os
import sys
import scanpy as sc
import muon as mu
import mudata as mu

import numpy as np
import mplscience
import matplotlib.pyplot as plt
import pickle
import pandas as pd
import seaborn as sns
import torch
import pymde #to run MDE
pymde.seed(0)

print("Global configurations")
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)
# sc.set_figure_params(figsize=(6, 6), frameon=False)
scvi.settings.seed = 0  # optional: ensures reproducibility
pymde.seed(0)
#sns.set_theme()
if torch.cuda.is_available():
    print("CUDA is available")
    print("Using device:", torch.cuda.get_device_name())
    torch.set_float32_matmul_precision("high")

print("Reading integrated ref+query latent space")  
totalvi_integrated = pd.read_csv(totalvi_integrated_file, index_col = 0, header = 0)

mde = pymde.preserve_neighbors(
    torch.tensor(totalvi_integrated.values, dtype=torch.float32,device='cuda:0'),
    embedding_dim=2,
    constraint=pymde.Standardized(),
    repulsive_fraction=0.7,
    n_neighbors = 15,
    verbose=True,
    device = 'cuda:0'
)

mde = pymde.preserve_neighbors(
    torch.tensor(totalvi_integrated.values, dtype=torch.float32,device='cuda:0'),
    embedding_dim=2,
    attractive_penalty='pymde.functions.penalties.Log1p', 
    repulsive_penalty='pymde.functions.penalties.Log'
    constraint=None,
    repulsive_fraction=None,
    n_neighbors = None,
    verbose=True,
    device = 'cuda:0'
)


import pickle
model_pkl_file = prefix+"/mde_model.pkl"  
with open(model_pkl_file, 'wb') as file:  
    pickle.dump(mde, file)

# with open(model_pkl_file, 'rb') as file:  
#     model = pickle.load(file)

embedding = mde.embed(verbose=True)
mde_df = pd.DataFrame(embedding.cpu(), index = totalvi_integrated.index) 
mde_df.to_csv(prefix+"/mde2.csv", index=True)

pairs, distorsions = mde.high_distortion_pairs()
pairs_df = pd.DataFrame(pairs.cpu(), columns=['cell1', 'cell2'])
pairs_df['cell1'] = totalvi_integrated.index[pairs_df['cell1']]
pairs_df['cell2'] = totalvi_integrated.index[pairs_df['cell2']]
distorsions_df = pd.DataFrame(distorsions.cpu(),columns=['distortion'])
pairs_df['distortion'] = distorsions_df['distortion']
#pairs_df.sample(n=1000000, replace=False).to_csv(prefix+"/mde_distorsions_sample.csv")
pairs_df.to_csv(prefix+"/mde_distorsions.csv")
#most_distorted_pairs = pairs[:500]
mde.distortions_cdf()
fig = plt.gcf() 
fig.savefig(prefix+"/mde_distorsion_cdf.png")

```


**Annotation 20250109**

```{r}
so_orig = readRDS("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/igt1_96_withtotalvi20250109_level1only.Rds")
mypal_level1 = setNames(mypal, unique(so_orig$annotation_level1))
mypal_level2 = setNames(mypal, unique(so_orig$annotation_level2))
setwd("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DP")
so = so_orig[,so_orig$annotation_level1 == "abT_DP"]

dir_with_file = "/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/totalvi_20241008_rmIGTsample"
so = AddLatentData(so, latent_file = sprintf("%s/latent.csv",dir_with_file), prefix = "totalvi_20241008_rmIGTsample", calculate_umap = F)
dir_with_file = "/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DP/20250109_abT_DP"
so = AddLatentData(so, latent_file = sprintf("%s/mde2.csv",dir_with_file), prefix = "mde_incremental", calculate_umap = F)

```

Transfer labels

```{r}
MyTransferLabels = function(cell_embeddings_ref, cell_embeddings_query, labels_ref = as.character(so$annotation_level2_20241216[so$is_ref == "ref"]), n_neighbors = 30) {
    require(RcppAnnoy)
    # cell_embeddings_ref = so[["totalvi_20241008_rmIGTsample"]]@cell.embeddings[so$is_ref == "ref",]
    # cell_embeddings_query = so[["totalvi_20241008_rmIGTsample"]]@cell.embeddings[so$is_ref == "query",]
    # labels_ref = as.character(so$annotation_level2_20241216[so$is_ref == "ref"])
    
    # Use the Annoy algorithm to find nearest neighbors between query and ref datasets
    message(sprintf("Number of nearest neighbors to find betweeen query and ref: %s", n_neighbors))
    
    message("Create Annoy index for ref dataset")
    annoy_index = new(AnnoyAngular, ncol(cell_embeddings_ref)) ##use cosine distance Angular
    for (i in 1:nrow(cell_embeddings_ref)) {
        annoy_index$addItem(i - 1, cell_embeddings_ref[i, ])
    }
    annoy_index$build(10)  # Build the index with 10 trees
    
    message("Find nearest ref neighbors for each cell in query dataset")
    nn_indices <- t(sapply(1:nrow(cell_embeddings_query), function(i) {
        annoy_index$getNNsByVector(cell_embeddings_query[i, ], n_neighbors)
    }))
    
    # nn_indices gives you the indices of nearest neighbors in the ref dataset
    # the rows are cells from query dataset, columns are the 30 nearest cells in the ref dataset
    # dim(nn_indices)
    # head(nn_indices)
    
    message("Transfer labels based on majority vote from nearest neighbors")
    transfer_labels <- apply(nn_indices, 1, function(neighbors) {
        # Get labels for the nearest neighbors
        neighbor_labels <- labels_ref[neighbors + 1]  # Add 1 for R's 1-based index
        
        # Return the most common label (majority vote)
        most_common_label <- names(sort(table(neighbor_labels), decreasing = TRUE))[1]
        return(most_common_label)
    })
    
    names(transfer_labels) = rownames(cell_embeddings_query)
    
    return(transfer_labels)
}

so$level2_new = as.character(so$annotation_level2_20241216)
so$level2_new[so$annotation_level2_parent1 == "proliferating"] = "abT_DP_prolif"
so$level2_new[so$annotation_level2_parent1 == "miniverse"] = "abT_DP_miniverse"
# so$level2_new[so$annotation_level2_parent1 == "preT"] = "CD4_preT"
table(so$level2_new, so$annotation_level1)
table(so$level2_new, so$annotation_level2_parent1)

so$is_ref = "other"
so$is_ref[so$annotation_level1 == "abT_DP" & so$annotation_level1_20241216 == "abT_DP"] = "ref"
so$is_ref[so$annotation_level1 == "abT_DP" & so$annotation_level1_20241216 != "abT_DP"] = "query"
so$is_ref[so$annotation_level2_parent1 %in% c("miniverse")] = "other" #"proliferating", "preT"
cell_embeddings_ref = so[["totalvi_20241008_rmIGTsample"]]@cell.embeddings[so$is_ref == "ref",]
cell_embeddings_query = so[["totalvi_20241008_rmIGTsample"]]@cell.embeddings[so$is_ref == "query",]
labels_ref = as.character(so$annotation_level2_20241216[so$is_ref == "ref"])

transfer_labels = MyTransferLabels(cell_embeddings_ref, cell_embeddings_query, labels_ref, n_neighbors = 30)
so$level2_new[so$is_ref == "query"] = transfer_labels
table(transfer_labels)

table(so$annotation_level2_parent1, so$level2_new)
table(so$annotation_level1, so$level2_new)
table(so$annotation_level2_20241216, so$level2_new)

```

Check transfer and readjust clusters if needed, i.e. add new clusters
abT_DP_cl18 in 18,57,58

```{r}
so = NormalizeData(so)
FeaturePlot(so, reduction = "mde_incremental",slot = "data", features = "Mki67", order = T, raster = T, raster.dpi = c(1024,1024))

prefix_latent = "totalvi_20241008_rmIGTsample"
n_latent = ncol(so[[prefix_latent]]@cell.embeddings)
so = FindNeighbors(so, dims = 1:n_latent, reduction = prefix_latent)
so = FindClusters(so, resolution = 0.5, cluster.name = sprintf("Cluster_%s_Res0.5",prefix_latent))
so = FindClusters(so, resolution = 0.75, cluster.name = sprintf("Cluster_%s_Res0.75",prefix_latent))
so = FindClusters(so, resolution = 1, cluster.name = sprintf("Cluster_%s_Res1",prefix_latent))

pdf(sprintf("%s/MDE_annotation_20250109_TransferLabels_Reclustering_to_see.pdf", "20250109_abT_DP"), 20, 20, useDingbats = F)
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level1", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal_level1)
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level1_20241216", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal)
DimPlot(so, reduction = "mde_incremental", group.by = "level2_new", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal_level2) + ggtitle("transfer labels from annotation_level2_20241216")
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level2_20241216", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal_level2)
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level2_parent1", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal)
DimPlot(so, reduction = "mde_incremental", group.by = sprintf("Cluster_%s_Res0.5",prefix_latent), raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal)
DimPlot(so, reduction = "mde_incremental", group.by = sprintf("Cluster_%s_Res0.75",prefix_latent), raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal)
DimPlot(so, reduction = "mde_incremental", group.by = sprintf("Cluster_%s_Res1",prefix_latent), raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal)
FeaturePlot(so, reduction = "mde_incremental",slot = "data", features = "Mki67", order = T, raster = T, raster.dpi = c(1024,1024))
dev.off()

so$level2_new[so$annotation_level2_parent1  %in% c("proliferating") | so[["mde_incremental"]]@cell.embeddings[,1] < -2] = "abT_DP_prolif"

so$level2_new[so$Cluster_totalvi_20241008_rmIGTsample_Res0.75 %in% "0"] = "abT_DP_cl51"
so$level2_new[so$Cluster_totalvi_20241008_rmIGTsample_Res0.75 %in% "1"] = "abT_DP_cl59"
so$level2_new[so$Cluster_totalvi_20241008_rmIGTsample_Res0.75 %in% "2"] = "abT_DP_cl60"
so$level2_new[so$Cluster_totalvi_20241008_rmIGTsample_Res0.75 %in% "3"] = "abT_DP_cl61"
so$level2_new[so$Cluster_totalvi_20241008_rmIGTsample_Res0.75 %in% "4"] = "abT_DP_cl62"
so$level2_new[so$Cluster_totalvi_20241008_rmIGTsample_Res0.75 %in% "9"] = "abT_DP_cl63"
so$level2_new[so$Cluster_totalvi_20241008_rmIGTsample_Res0.75 %in% "7"] = "abT_DP_cl64"
so$level2_new[so$Cluster_totalvi_20241008_rmIGTsample_Res0.75 %in% "11"] = "abT_DP_cl65"
so$level2_new[so$annotation_level2_parent1  %in% c("miniverse")] = "abT_DP_miniverse"
so$level2_new[so$annotation_level2_parent1  %in% c("proliferating") | so[["mde_incremental"]]@cell.embeddings[,1] < -2] = "abT_DP_prolif"

# DimPlot(so, reduction = "mde_incremental", cells = names(so$level2_new[so$Cluster_totalvi_20241008_rmIGTsample_Res1 %in% "25" & so[["mde_incremental"]]@cell.embeddings[,1] < 1 ]), raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal_level2)

# so$annotation_level2_parent1 = "not_applicable"
# annot$level2_parent1[annot$level2 %in% c("CD4_cl10", "CD4_cl13", "CD4_cl14", "CD4_cl15", "CD4_cl16", "CD4_cl17", "CD4_cl18", "CD4_cl20", "CD4_cl21", "CD4_cl22", "CD4_cl23", "CD4_cl25", "CD4_cl9", "CD8AB_cl10", "CD8AB_cl11", "CD8AB_cl12", "CD8AB_cl13", "CD8AB_cl14", "CD8AB_cl15", "CD8AB_cl18", "CD8AB_cl20", "CD8AB_cl6", "CD8AB_cl7","treg_cl2", "treg_cl3", "treg_cl4", "treg_cl6", "treg_cl8")] = "activated"
# so$annotation_level2_parent1[so$annotation_level2 %in% c("CD4_cl1", "CD4_cl12", "CD4_cl2", "CD4_cl3", "CD4_cl4", "CD4_cl5", "CD4_cl7", "CD8AB_cl1", "CD8AB_cl2", "CD8AB_cl22", "CD8AB_cl4", "CD8AB_cl5","treg_cl1", "treg_cl7")] = "resting"
# so$annotation_level2_parent1[so$annotation_level2 %in% c("CD4_cl8", "CD8AB_cl19", "treg_cl5","not_CD4CD8_cl48")] = "proliferating"
# table(so$annotation_level2_parent1, so$annotation_level2)

#rerun annotation_level2_parent1 since new annotated cells from transfer labels etc
so$annotation_level2_parent1[so$level2_new %in% c("abT_DP_prolif") | so$annotation_level2_parent1  %in% c("proliferating") ] = "proliferating"
so$annotation_level2_parent1[!so$level2_new %in% c("abT_DP_prolif", "abT_DP_miniverse", "not_CD4CD8_cl48", "abT_DP_prolif")] = "other"
table(so$annotation_level2_parent1, so$level2_new)

pdf(sprintf("%s/MDE_annotation_20250109_level2.pdf", "20250109_abT_DP"), 20, 20, useDingbats = F)
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level1", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal_level1)
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level1_20241216", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal)
DimPlot(so, reduction = "mde_incremental", group.by = "level2_new", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal) + ggtitle("After transfer labels and reclustering")
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level2_20241216", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal_level2)
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level2_parent1", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal)
dev.off()

if (all(colnames(so_orig)[so_orig$annotation_level1 == "abT_DP"] == colnames(so))) {
    print("True")
    so_orig$annotation_level2[so_orig$annotation_level1 == "abT_DP"] = so$level2_new[colnames(so_orig)[so_orig$annotation_level1 == "abT_DP"]]
    so_orig$annotation_level2_parent1[so_orig$annotation_level1 == "abT_DP"] = so$annotation_level2_parent1[colnames(so_orig)[so_orig$annotation_level1 == "abT_DP"]]
}

table(so_orig$annotation_level2_parent1[so_orig$annotation_level1 == "abT_DP"], so_orig$annotation_level2[so_orig$annotation_level1 == "abT_DP"])
table(so_orig$annotation_level2[so_orig$annotation_level1 == "abT_DP"], so_orig$annotation_level2_20241216[so_orig$annotation_level1 == "abT_DP"])

#Export to save awaiting the other annotations
annot = data.frame(cell_id = colnames(so_orig), so_orig@meta.data[,c("annotation_level1", "annotation_level2", "annotation_level2_parent1", "nonconv_tcr_recog")])
colnames(annot) = c("cell_id", "level1", "level2", "level2_parent1", "nonconv_tcr_recog")
table(annot$level2_parent1, annot$level1)
sum(rowSums(apply(annot,2,is.na)))
write.table(x = annot, file = "../annotation_table_20250109_withlevel2CD8AB_CD4_gdT_nonconv_CD8aa_DN_DP.csv", row.names = F, quote = F, sep = ",")


```

Check Prolif clusters

```{r}
setwd("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DP")
so = so_orig[,so_orig$annotation_level1 == "abT_DP"]
so = NormalizeData(so)
so$is_prolif = so$S.Score >0.07 | so$G2M.Score >0.2
dir_with_file = "/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DP/20250109_abT_DP"
so = AddLatentData(so, latent_file = sprintf("%s/mde2.csv",dir_with_file), prefix = "mde_incremental", calculate_umap = F)

pdf(sprintf("%s/Prolif_scores_MDE_tosee.pdf","."), 10, 10, useDingbats = F)
FeaturePlot(so, reduction = "mde_incremental", slot = "data", features = "S.Score", order = F, raster = T, raster.dpi = c(1024,1024))
FeaturePlot(so, reduction = "mde_incremental", slot = "data", features = "G2M.Score", order = F, raster = T, raster.dpi = c(1024,1024))
DimPlot(so, reduction = "mde_incremental", group.by = "is_prolif", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = c("grey", "red"))
MyDimPlotHighlight(so, umap_to_plot = "mde_incremental", cells_to_highlight = names(which(so$is_prolif)), highlight_column_name ="is_prolif", highlight_size = 0.5, highlight_alpha = 0.5, pixels = c(512, 512), mycols = c("grey","red"), label = F, print_plot1 = T, print_plot2 = F )
MyDimPlotHighlight(so, umap_to_plot = "mde_incremental", cells_to_highlight = names(which(so$annotation_level2_parent1 == "proliferating")), highlight_column_name ="annotation_level2_parent1", highlight_size = 0.5, highlight_alpha = 0.5, pixels = c(512, 512), mycols = mypal_level2_parent1, label = F, print_plot1 = T, print_plot2 = F )
dev.off()
```


export data
```{r}
# so_orig = readRDS("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/igt1_96_withtotalvi20250109.Rds")
so_orig = readRDS("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/igt1_96_withtotalvi20250212.Rds")

setwd("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/DP")
so = so_orig[,so_orig$annotation_level1 == "DP"]

# dir_with_file = "/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/totalvi_20241008_rmIGTsample"
# so = AddLatentData(so, latent_file = sprintf("%s/latent.csv",dir_with_file), prefix = "totalvi_20241008_rmIGTsample", calculate_umap = F)
dir_with_file = "/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/abT_DP/20250109_abT_DP"
so = AddLatentData(so, latent_file = sprintf("%s/mde2.csv",dir_with_file), prefix = "mde_incremental", calculate_umap = F)

so[["umap_totalvi_20241006"]] = NULL
so[["mde_totalvi_20241006"]] = NULL
so[["umap2_totalvi_20241006"]] = NULL
so[["mdeumap_totalvi_20241006"]] = NULL
so[["umap_totalvi_20241008_rmIGTsample"]] = NULL
so[["mde_totalvi_20241008_rmIGTsample"]] = NULL
so[["mde2_totalvi_20241008_rmIGTsample"]] = NULL
so[["mdeumap_totalvi_20241008_rmIGTsample"]] = NULL
so[["mde_totalvi_20241029_fitleredGenesProt"]] = NULL
so[["umap_totalvi_20241029_fitleredGenesProt"]] = NULL


pdf(sprintf("%s/MDE_AnnotationLevel20250109.pdf", "."), 10, 10, useDingbats = F)
MyDimPlotHighlight(so_orig, umap_to_plot = "mde2_totalvi_20241006", cells_to_highlight = names(which(so_orig$annotation_level1 == "DP")), highlight_column_name ="annotation_level2", highlight_size = 0.5, highlight_alpha = 0.5, pixels = c(512, 512), mycols = mypal_level2, print_plot1 = T, print_plot2 = T, labelclusters = T )
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level2", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal_level2)
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level2", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal_level2) + theme_void() + NoLegend() 
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level2_group", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal_level2_group)
DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level2_group", raster = T, raster.dpi = c(512,512), label = T) + scale_color_manual(values = mypal_level2_group) + theme_void() + NoLegend() 
dev.off()

# saveRDS(so, file = "igt1_96_DP_20250109.Rds")
saveRDS(so, file = "igt1_96_DP_20250212.Rds")


```

