---
output: html_document
editor_options: 
  chunk_output_type: console
---
**Initialize: load libraries and custom functions**

```{bash}
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=jfkfloor2 --qos=jfkfloor2 --nodes=1 
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=beagle3-bigmem --nodes=1 
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=zemmour-hm --qos=zemmour --nodes=1 
sinteractive --time=03:00:00 --account=pi-zemmour --partition=caslake --nodes=1 --mem=96GB

module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13
source activate /project/zemmour/david/envs/scvi_20240315
#source activate /project/zemmour/david/envs/r443
module load openblas/0.3.13

cd /project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/CD4
```


```{r}
setwd("~/google_drive_uchicago/ImmgenT/analysis/data_integration/IGT1_96/CD4")
libs = c("ZemmourLib","forcats", "gridExtra","patchwork", "Matrix", "Seurat", "ggplot2", "dplyr", "reshape2", "ggrastr","scattermore", "RColorBrewer", "pals", "scales", "pheatmap", "rafalib") 
sapply(libs, function(x) suppressMessages(suppressWarnings(library(x, character.only = TRUE, quietly = T, warn.conflicts  = F))))
#source("/project/jfkfloor2/zemmourlab/david/immgent/immgent_integration_git/custom_functions_david.R")

ColorRamp = rev(colorRampPalette(brewer.pal(n = 7,name = "RdYlBu"))(100))
ColorRamp = rev(colorRampPalette(c('red','white','blue'))(20))
ColorRamp = rev(rainbow(10, end = 4/6))
ColorRamp = rev(viridis(100))
ColorRamp = brewer.pal(9, "Blues")

#mycol = c("black","blue","red","darkgreen", "orange","purple", "cyan", "greenyellow",    "salmon", "magenta","pink", "tan", "brown") # c("magenta", "red",  "darkgreen", "cyan", "blue", "blue", "blue", "black", "blue", "blue", "blue", "blue", "orange")

mypal_level2 = immgent_colors$level2
mypal_level2["not classified"] = "black"
# names(mypal_level2) = gsub("nonconv", replacement = "Tz",names(mypal_level2) )
# mypal_level2 = immgent_colors$level2_option2
# mypal_level2["not classified"] = "black"
mypal_level1 = immgent_colors$level1
mypal_level1["not classified"] = "black"
# names(mypal_level1) = gsub("nonconv", replacement = "Tz",names(mypal_level1) )
mypal_organ = immgent_colors$organ_simplified
mypal_level2group = c("resting" = "blue", "activated" = "red", "miniverse" = "darkgreen", "proliferating" = "black", "other" = "grey", "preT" = "grey" )

#Large Color palette
library("pals")
n = 70
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
mypal1 = unique(unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals))))
mypal1 = mypal1[-4]
mypal = c(glasbey(), polychrome(), mypal1)
names(mypal) = NULL
#pal.bands(mypal, main="Colormap suggestions")
# mypal_organ = setNames(mypal, unique(so$organ_simplified))
# mypal_organ = mypal_organ[!is.na(names(mypal_organ))]
# mypal_level1 = setNames(mypal, unique(so$annotation_level1))
# mypal_level1 = mypal_level1[!is.na(names(mypal_level1))]
# mypal_level2 = setNames(mypal, unique(so_orig$annotation_level2))
# mypal_level2 = mypal_level2[!is.na(names(mypal_level2))]
# mypal_level2["CD4_cl18"] = "blue"
mypal_igt = setNames(mypal, unique(so_orig$IGT))
mypal_igt = mypal_igt[!is.na(names(mypal_igt))]

```

```{r}
so_orig = readRDS("igt1_96_withtotalvi20260206_clean_ADTonly.Rds")

cd4_cells <- colnames(so_orig)[so_orig$annotation_level1 == "CD4"]

makeEmbeddingRasterCache(
    so = so_orig,
    reduction = "mde2_totalvi_20241006",
    cells = colnames(so_orig),
    outfile_prefix = "immgenT_allT_MDE_background",
    point_size = 0.3,
    point_color = "grey",
    point_alpha = 0.5,
    width = 1024,
    height = 1024
)

makeEmbeddingRasterCache(
    so = so_orig,
    reduction = "mde_incremental",
    cells = colnames(so_orig)[so_orig$annotation_level1 == "CD8"],
    outfile_prefix = "immgenT_CD8_MDE_background",
    point_size = 0.3,
    point_color = "grey",
    point_alpha = 0.5,
    width = 1024,
    height = 1024
)

makeEmbeddingRasterCache(
    so = so_orig,
    reduction = "mde_incremental",
    cells = colnames(so_orig)[so_orig$annotation_level1 == "CD4"],
    outfile_prefix = "immgenT_CD4_MDE_background",
    point_size = 0.3,
    point_color = "grey",
    point_alpha = 0.5,
    width = 1024,
    height = 1024
)

makeEmbeddingRasterCache(
    so = so_orig,
    reduction = "mde_incremental",
    cells = colnames(so_orig)[so_orig$annotation_level1 == "Treg"],
    outfile_prefix = "immgenT_Treg_MDE_background",
    point_size = 0.3 ,
    point_color = "grey",
    point_alpha = 0.3,
    width = 512,
    height = 512
)

makeEmbeddingRasterCache(
    so = so_orig,
    reduction = "mde_incremental",
    cells = colnames(so_orig)[so_orig$annotation_level1 == "gdT"],
    outfile_prefix = "immgenT_gdT_MDE_background",
    point_size = 0.3,
    point_color = "grey",
    point_alpha = 0.5,
    width = 512,
    height = 512
)

makeEmbeddingRasterCache(
    so = so_orig,
    reduction = "mde_incremental",
    cells = colnames(so_orig)[so_orig$annotation_level1 == "CD8aa"],
    outfile_prefix = "immgenT_CD8aa_MDE_background",
    point_size = 0.3,
    point_color = "grey",
    point_alpha = 0.5,
    width = 512,
    height = 512
)

makeEmbeddingRasterCache(
    so = so_orig,
    reduction = "mde_incremental",
    cells = colnames(so_orig)[so_orig$annotation_level1 == "DN"],
    outfile_prefix = "immgenT_DN_MDE_background",
    point_size = 0.3,
    point_color = "grey",
    point_alpha = 0.5,
    width = 512,
    height = 512
)

makeEmbeddingRasterCache(
    so = so_orig,
    reduction = "mde_incremental",
    cells = colnames(so_orig)[so_orig$annotation_level1 == "DP"],
    outfile_prefix = "immgenT_DP_MDE_background",
    point_size = 0.3,
    point_color = "grey",
    point_alpha = 0.5,
    width = 512,
    height = 512
)


```


```{r}
so_query = readRDS('/Users/david/Library/CloudStorage/GoogleDrive-zemmour@uchicago.edu/My Drive/ImmgenT/20250109_freeze/odhran/CD4/GSE200635_IAb_Tet_LCMV/Trial_Final/Final_Seurat_object.Rds') 
so_query$cellID = colnames(so_query)
so_query@meta.data %>% count(sample_name, IGTHT)
so_query$sample_name[so_query$IGTHT == "Batch1_GSM6040471"] = "MC38GP66_dLN_TIL_GSE200635"
so_query$sample_type = NA
so_query$sample_type[so_query$IGTHT == "Batch1_GSM6040471"] = "MC38GP66_dLN_TIL"
so_query$annotations = NA
so_query$organ_simplified = "dLN_Tumor"
so_query$target_cells_simplified = "CD4pGP66Tetp"
so_query$Ag_spe = "GP66:I-Ab"
so_query$infection_phase = NA
sub = so_query@meta.data %>% filter(!(level2_final %in% c("not classified"))) %>% row.names()
so_query = so_query[,sub]
so_query@meta.data %>% count(sample_name, sample_type, organ_simplified, target_cells_simplified, Ag_spe, Ag_spe)
queries[["GSE200635_Andreatta_Tumor"]] = so_query


p <- DimPlot(
  so_query,
  reduction = "mde_incremental_level2",
  group.by = "level2_final",
  cols = mypal_level2,pt.size = 2,
  raster = F
)

bg <- AddEmbeddingRasterBackground("DP", interpolate = F, color = "grey", alpha = 0.5)

p$layers <- c(list(bg), p$layers)

p + coord_fixed() + xlim(c(-2, 4)) + ylim(c(-3, 3))




```


