

**Install SCVI --> /project/jfkfloor2/zemmourlab/david/envs/scvi**
```{bash}
ssh -Y CNETID@midway3.rcc.uchicago.edu

cd /project/zemmour/youssef

module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 

source activate mamba-env  
mamba create -p /project/zemmour/david/envs/scvi python=3.9
#log out and log back in to activate the new environment
source activate /project/zemmour/youssef/envs/scvi

mamba install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
mamba install jax jaxlib -c conda-forge

mamba install scvi-tools -c conda-forge

#check installation and GPU works:
sinteractive --time=12:00:00 --account=pi-zemmour --partition=gpu --gres=gpu:1 —-mem=8GB
module load python/anaconda-2022.05
source activate /project/zemmour/youssef/envs/scvi
#on midway3-0283 GPU
#import torch
#torch.cuda.is_available()
#True
#torch.cuda.device_count()
#1
#torch.cuda.current_device()
#0
#torch.cuda.device(0)
#<torch.cuda.device object at 0x7f4d19f42af0>
#torch.cuda.get_device_name(0)
#'Quadro RTX 6000'

#install R in this environment, if needed
mamba install -c conda-forge r-base=4.2 r-essentials r-reticulate
#then install seuratv5, BP cells, ggrastr 
module load hdf5/1.12.0 #for BPCells but also others


```



**Install scvi-tools 1.1.2 for HotSpot --> /project/zemmour/david/envs/scvi_20240315**
just in case it messes up my SCVI environment
scvi-tools 1.1.2

```{bash}
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #need this one to avoid cblas_ somthing error when loading packages

source activate /project/jfkfloor2/zemmourlab/david/envs/scvi
conda env export > scvi.yml
#modifyyml to change the name to /project/zemmour/david/envs/scvi_20240315
#exit and log in again
source activate mamba-env  
mamba env create -p /project/zemmour/david/envs/scvi_20240315 -f scvi.yml
#if issues with "strict repo priority", delete the line in .condarc

module load python/anaconda-2022.05
source activate /project/zemmour/david/envs/scvi_20240315

mamba update scvi-tools #to 1.1.2
pip install hotspot


```

**Install COMETSC**

```{bash}
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #

source activate mamba-env  
mamba create -p /project/zemmour/david/envs/cometsc python=3.6

source activate /project/zemmour/david/envs/cometsc
pip install COMETSC


```

**Install scArches**

Trial 9 WORKED!
```{bash}
cd /project/zemmour/david/envs/
module load python/anaconda-2022.05 
conda create -p /project/zemmour/david/envs/scarches_test9 python=3.9

source activate /project/zemmour/david/envs/scarches_test9

pip3 install torch torchvision
pip install -U scarches

sinteractive --time=00:10:00 --account=pi-zemmour --partition=gpu --gres=gpu:1 --mem=32GB

source activate /project/zemmour/david/envs/scarches_test9

python
import torch
torch.cuda.is_available()

import warnings
warnings.simplefilter(action='ignore')
import scanpy as sc
import torch
import scarches as sca
import numpy as np
import gdown
import mudata as mu
import os
import pandas as pd
import matplotlib.pyplot as plt

#torch.cuda.is_available()

```

Trial 1: works but only on CPU
```{bash}
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #

source activate mamba-env  
cd /project/zemmour/david/envs/
git clone https://github.com/theislab/scarches
cd scarches
mamba env create -p /project/zemmour/david/envs/scarches_20240424 -f envs/scarches_linux.yaml

source activate /project/zemmour/david/envs/scarches_20240424



```

Trial 2: doesn't recog GPU
```{bash}
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13
module load cuda/11.7

source activate mamba-env  
mamba create -p /project/zemmour/david/envs/scarches_test python=3.7
#log out and log back in to activate the new environment
source activate /project/zemmour/david/envs/scarches_test

mamba install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
mamba install jax jaxlib -c conda-forge

pip install -U scarches

sinteractive --time=1:00:00 --account=pi-zemmour --partition=beagle3 --gres=gpu:1 --mem=8GB
module load python/anaconda-2022.05 
module load hdf5/1.12.0
module load openblas/0.3.13 
module load cuda/11.7
source activate /project/zemmour/david/envs/scarches_test
#on midway3-0283 GPU
#import torch
#torch.cuda.is_available()
#True
#torch.cuda.device_count()
#1
#torch.cuda.current_device()
#0
#torch.cuda.device(0)
#<torch.cuda.device object at 0x7f4d19f42af0>
#torch.cuda.get_device_name(0)
#'Quadro RTX 6000'


```

Trial 3: doesn't work at all
```{bash}
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 
source activate /project/jfkfloor2/zemmourlab/david/envs/scvi
conda env export > /project/zemmour/david/envs/scvi_ref_dependencies_for_gpu.yml
#modify yml to change the name to /project/zemmour/david/envs/mrvi_test5
#exit and log in again
source activate mamba-env  
mamba env create -p /project/zemmour/david/envs/mrvi_test5 -f formrvitest5.yml
#if issues with "strict repo priority", delete the line in .condarc
source activate /project/zemmour/david/envs/mrvi_test5
```

Trial 4: nope
```{bash}
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13
module load cuda/11.7

source activate mamba-env  
mamba create -p /project/zemmour/david/envs/scarches_test2 python=3.8
#log out and log back in to activate the new environment
source activate /project/zemmour/david/envs/scarches_test2

mamba install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
#mamba install jax jaxlib -c conda-forge

pip install -U scarches

sinteractive --time=1:00:00 --account=pi-zemmour --partition=beagle3 --gres=gpu:1 --mem=8GB
module load python/anaconda-2022.05 
module load hdf5/1.12.0
module load openblas/0.3.13 
module load cuda/11.7
source activate /project/zemmour/david/envs/scarches_test2
#on midway3-0283 GPU
#import torch
#torch.cuda.is_available()

```

Trial 5:still no GPU
```{bash}
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #

source activate mamba-env  
cd /project/zemmour/david/envs/
git clone https://github.com/theislab/scarches
cd scarches
mamba env create -p /project/zemmour/david/envs/scarches_20240424 -f envs/scarches_linux.yaml

source activate /project/zemmour/david/envs/scarches_20240424

#install pytorch
mamba install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13
module load cuda/11.7
source activate /project/zemmour/david/envs/scarches_20240424

```


Trial 6: nope
```{bash}
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13
module load cuda/11.7

source activate /project/jfkfloor2/zemmourlab/david/envs/scvi
conda env export > /project/zemmour/david/envs/scvi_ref_dependencies_for_gpu.yml

source activate mamba-env  
mamba env create -p /project/zemmour/david/envs/scarches_test3 -f /project/zemmour/david/envs/scvi_ref_dependencies_for_gpu.yml python=3.9
#log out and log back in to activate the new environment
source activate /project/zemmour/david/envs/scarches_test3 
#pip uninstall scvi-tools

#pip install -U scarches #didn't work

git clone https://github.com/theislab/scarches
cd scarches
python3 setup.py install --prefix=/project/zemmour/david/envs/scarches_test3/scarches #bugs


```

Trial 7
```{bash}
module load python/anaconda-2021.05
module load cuda/11.2
#module load hdf5/1.12.0 #for BPCells but also others
#module load openblas/0.3.13 #

source activate mamba-env  
mamba create -p /project/zemmour/david/envs/scarches_test4 python=3.8
#log out and log back in to activate the new environment
source activate /project/zemmour/david/envs/scarches_test4

conda install pytorch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0 cudatoolkit=11.3 -c pytorch -c conda-forge

pip install -U scarches

sinteractive --time=1:00:00 --account=pi-zemmour --partition=beagle3 --gres=gpu:1 --mem=8GB
module load python/anaconda-2022.05 
module load hdf5/1.12.0
module load openblas/0.3.13 
module load cuda/11.7
source activate /project/zemmour/david/envs/scarches_test2
#on midway3-0283 GPU
#import torch
#torch.cuda.is_available()


```

Trial 8: python 3.8 sounds wrong sca didn't install, but torch did
```{bash}
cd /project/zemmour/david/envs/
module load python/anaconda-2022.05 
conda create -p /project/zemmour/david/envs/scarches_test8 python=3.8

source activate /project/zemmour/david/envs/scarches_test8

pip3 install torch torchvision

sinteractive --time=00:10:00 --account=pi-zemmour --partition=gpu --gres=gpu:1 --mem=32GB

source activate /project/zemmour/david/envs/scarches_test8

pip install -U scarches

python
import torch
torch.cuda.is_available()

```

Trial 9:
```{bash}
cd /project/zemmour/david/envs/
module load python/anaconda-2022.05 
conda create -p /project/zemmour/david/envs/scarches_test9 python=3.9

source activate /project/zemmour/david/envs/scarches_test9

pip3 install torch torchvision

sinteractive --time=00:10:00 --account=pi-zemmour --partition=gpu --gres=gpu:1 --mem=32GB

source activate /project/zemmour/david/envs/scarches_test9

pip install -U scarches

python
import torch
torch.cuda.is_available()

```

**Install mrVI**

Create a new environment in Midway3 for mrVI

```{bash}
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #need this one to avoid cblas_ somthing error when loading packages
source activate /project/jfkfloor2/zemmourlab/david/envs/scvi
conda env export > formrvitest5.yml
#modify yml to change the name to /project/zemmour/david/envs/mrvi_test5
#exit and log in again
source activate mamba-env  
mamba env create -p /project/zemmour/david/envs/mrvi_test5 -f formrvitest5.yml
#if issues with "strict repo priority", delete the line in .condarc
source activate /project/zemmour/david/envs/mrvi_test5
pip uninstall scvi-tools

pip install "jax[cuda12_pip]==0.4.14" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

pip install git+https://github.com/scverse/scvi-tools.git --no-deps

```


```{bash}
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13

####Try1: works but not on GPU
source activate mamba-env  
mamba create -p /project/zemmour/david/envs/scvi113_20240525 python=3.9
source activate /project/zemmour/david/envs/scvi113_20240525
conda install scvi-tools -c conda-forge 
pip install git+https://github.com/scverse/scvi-tools.git #updates to 1.1.3
conda install -c conda-forge scanpy python-igraph leidenalg
conda install -c pytorch -c conda-forge pymde


### doesn't work: GPU recognized but error with loading SCVI ImportError: cannot import name 'linear_util' from 'jax' (/project/zemmour/david/envs/mrvi_test5/lib/python3.9/site-packages/jax/__init__.py)
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #need this one to avoid cblas_ somthing error when loading packages
source activate /project/jfkfloor2/zemmourlab/david/envs/scvi
conda env export > formrvitest5.yml
#modify yml to change the name to /project/zemmour/david/envs/mrvi_test5
#exit and log in again
source activate mamba-env  
mamba env create -p /project/zemmour/david/envs/mrvi_test5 -f formrvitest5.yml
#if issues with "strict repo priority", delete the line in .condarc
source activate /project/zemmour/david/envs/mrvi_test5
pip install git+https://github.com/scverse/scvi-tools.git #updates to 1.1.3
pip install -U "jax[cuda12]"
#conda install jax=0.4.23 jaxlib=0.4.23 -c conda-forge #didn't work

It uninstall and installs this:
Installing collected packages: werkzeug, tensorboard-data-server, protobuf, multidict, ml-dtypes, grpcio, frozenlist, async-timeout, yarl, sparse, markdown, jaxlib, jax, aiosignal, xarray, tensorboard, numpyro, aiohttp, lightning, scvi-tools
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.1.0
    Uninstalling ml-dtypes-0.1.0:
      Successfully uninstalled ml-dtypes-0.1.0
  Attempting uninstall: jaxlib
    Found existing installation: jaxlib 0.4.7
    Uninstalling jaxlib-0.4.7:
      Successfully uninstalled jaxlib-0.4.7
  Attempting uninstall: jax
    Found existing installation: jax 0.4.8
    Uninstalling jax-0.4.8:
      Successfully uninstalled jax-0.4.8
  Attempting uninstall: numpyro
    Found existing installation: numpyro 0.11.0
    Uninstalling numpyro-0.11.0:
      Successfully uninstalled numpyro-0.11.0
  Attempting uninstall: scvi-tools
    Found existing installation: scvi-tools 0.20.3
    Uninstalling scvi-tools-0.20.3:
      Successfully uninstalled scvi-tools-0.20.3
Successfully installed aiohttp-3.9.5 aiosignal-1.3.1 async-timeout-4.0.3 frozenlist-1.4.1 grpcio-1.64.0 jax-0.4.28 jaxlib-0.4.28 lightning-2.2.5 markdown-3.6 ml-dtypes-0.4.0 multidict-6.0.5 numpyro-0.15.0 protobuf-5.27.0 scvi-tools-1.1.3 sparse-0.15.4 tensorboard-2.16.2 tensorboard-data-server-0.7.2 werkzeug-3.0.3 xarray-2024.5.0 yarl-1.9.4


### didn't work, same error: ImportError: cannot import name 'linear_util' from 'jax' (/project/zemmour/david/envs/mrvi_test5/lib/python3.9/site-packages/jax/__init__.py)
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #need this one to avoid cblas_ somthing error when loading packages
module load cuda/12.2
source activate /project/jfkfloor2/zemmourlab/david/envs/scvi
conda env export > formrvitest5.yml
#modify yml to change the name to /project/zemmour/david/envs/mrvi_test5
#exit and log in again
source activate mamba-env  
mamba env create -p /project/zemmour/david/envs/mrvi_test6 -f formrvitest5.yml
#if issues with "strict repo priority", delete the line in .condarc
source activate /project/zemmour/david/envs/mrvi_test6
pip install -U "jax[cuda12]"
pip install git+https://github.com/scverse/scvi-tools.git #updates to 1.1.3
conda install -c conda-forge scanpy python-igraph leidenalg
#conda install -c pytorch -c conda-forge pymde

### mrvi_test7: conda install jax=0.4.23 jaxlib=0.4.23 -c conda-forge doens't work
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #need this one to avoid cblas_ somthing error when loading packages
module load cuda/12.2
source activate /project/jfkfloor2/zemmourlab/david/envs/scvi
conda env export > formrvitest5.yml
#modify yml to change the name to /project/zemmour/david/envs/mrvi_test5
#exit and log in again
source activate mamba-env  
mamba env create -p /project/zemmour/david/envs/mrvi_test7 -f formrvitest5.yml
#if issues with "strict repo priority", delete the line in .condarc
source activate /project/zemmour/david/envs/mrvi_test7
conda install jax=0.4.23 jaxlib=0.4.23 -c conda-forge
#pip install -U "jax[cuda12]"
pip install git+https://github.com/scverse/scvi-tools.git #updates to 1.1.3
conda install -c conda-forge scanpy python-igraph leidenalg
conda install -c pytorch -c conda-forge pymde

### mrvi_test8: fails at mamba install pytorch...
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #need this one to avoid cblas_ somthing error when loading packages
module load cuda/12.2
source activate mamba-env  
mamba create -p /project/zemmour/david/envs/mrvi_test8 python=3.11
#if issues with "strict repo priority", delete the line in .condarc
source activate /project/zemmour/david/envs/mrvi_test8
mamba install pytorch torchvision torchaudio  -c pytorch -c nvidia #fails there
#pip install -U "jax[cuda12]"
#mamba install jax jaxlib -c conda-forge
#conda install jax=0.4.23 jaxlib=0.4.23 -c conda-forge
#pip install -U "jax[cuda12]"
pip install git+https://github.com/scverse/scvi-tools.git #updates to 1.1.3
conda install -c conda-forge scanpy python-igraph leidenalg
conda install -c pytorch -c conda-forge pymde


#### torch doesn't recognize CUDA
 #need this one to avoid cblas_ somthing error when loading packages
source activate mamba-env  
mamba create -p /project/zemmour/david/envs/mrvi_test3 python=3.9
source activate /project/zemmour/david/envs/mrvi_test3
mamba install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
mamba install jax jaxlib -c conda-forge

####New try: 
module load python/anaconda-2022.05 
source activate mamba-env  
mamba create -p /project/zemmour/david/envs/mrvi_test4 python=3.9
exit
module load python/anaconda-2022.05
source activate /project/zemmour/david/envs/mrvi_test4
mamba install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
mamba install jax jaxlib -c conda-forge


####doesn't work : didn't even download pytorch; cudatoolkit=12.2 isn't a thing
source activate mamba-env  
mamba create -p /project/zemmour/david/envs/mrvi_test python=3.9
source activate /project/zemmour/david/envs/mrvi_test
mamba install pytorch torchvision torchaudio tensorflow-gpu jax jaxlib scvi-tools -c pytorch -c nvidia -c conda-forge
pip install git+https://github.com/scverse/scvi-tools.git #updates to 1.1.3
#checking CUDA in my GPU session with command < nvidia-smi > shows CUDA 12.2
conda install -c conda-forge scanpy python-igraph leidenalg
conda install -c pytorch -c conda-forge pymde


###using scvi_20240524 env prior doesn't work
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #need this one to avoid cblas_ somthing error when loading packages
source activate /project/zemmour/david/envs/scvi_20240315
conda env export > scvi_20240315.yml
#modify yml to change the name to /project/zemmour/david/envs/mrvi_20240326
#exit and log in again
source activate mamba-env  
mamba env create -p /project/zemmour/david/envs/scvi_20240524 -f scvi113.yml
#if issues with "strict repo priority", delete the line in .condarc
source activate /project/zemmour/david/envs/scvi_20240524

conda install scvi-tools -c conda-forge

####didn't work
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #need this one to avoid cblas_ somthing error when loading packages
source activate mamba-env  
cd /project/zemmour/david/envs
mamba create -p /project/zemmour/david/envs/scvi113_mrvi python=3.9
source activate /project/zemmour/david/envs/scvi113_mrvi
mamba install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
mamba install jax jaxlib -c conda-forge
conda install scvi-tools -c conda-forge 
pip install git+https://github.com/scverse/scvi-tools.git #updates to 1.1.3


#### doesn't work on GPU, didn't install pytorch and jax before
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 #need this one to avoid cblas_ somthing error when loading packages
source activate mamba-env  
cd /project/zemmour/david/envs
mamba create -p /project/zemmour/david/envs/scvi113_20240525 python=3.9
source activate /project/zemmour/david/envs/scvi113_20240525
conda install scvi-tools -c conda-forge 
pip install git+https://github.com/scverse/scvi-tools.git #updates to 1.1.3

```

**Install scvi-tools 1.2.0 --> /project/zemmour/david/envs/scvi_20240315**
just in case it messes up my SCVI environment
scvi-tools 1.2.0


Worked!!!
```{python}
module load python

conda create -p /project/zemmour/david/envs/scvi120_20241008 python=3.10

source activate /project/zemmour/david/envs/scvi120_20241008

conda install cuda -c nvidia/label/cuda-12.4.0
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia

conda install jax jaxlib scvi-tools -c conda-forge

##check
sinteractive --time=0:10:00 --account=pi-zemmour --partition=beagle3 --gres=gpu:1 --mem=8GB
module load python
source activate /project/zemmour/david/envs/scvi120_20241008
#on midway3-0283 GPU
import torch
torch.cuda.is_available()
import scvi



```

intially troubleshooting that worked. Eventually installing jax jaxlib scvi-tools at the same time ensured compatibility. 
Use this environment to test compatibility of other packages before doing on scvi120_20241008 
```{bash}

module load python

conda create -p /project/zemmour/david/envs/scvi120_test4 python=3.10

source activate /project/zemmour/david/envs/scvi120_test4

conda install cuda -c nvidia/label/cuda-12.4.0
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia

pip install -U "jax[cuda12]"

conda install scvi-tools -c conda-forge

sinteractive --time=0:10:00 --account=pi-zemmour --partition=beagle3 --gres=gpu:1 --mem=8GB
module load python
source activate /project/zemmour/david/envs/scvi120_test4
#on midway3-0283 GPU
import torch
torch.cuda.is_available()
import scvi

conda remove scvi-tools
conda install jax jaxlib scvi-tools -c conda-forge

pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html ?
python -c "import jax; print(f'Jax backend: {jax.default_backend()}')"

pip install -U jax
conda install jax jaxlib scvi-tools -c conda-forge
conda install jaxlib==cuda jax cuda-nvcc -c conda-forge -c nvidia

conda install scanpy muon seaborn -c conda-forge
pip install mplscience

```

test3: fails, scvi ok but not torch
```{bash}

module load python

conda create -p /project/zemmour/david/envs/scvi120_test3 python=3.10

source activate /project/zemmour/david/envs/scvi120_test3

conda install cuda -c nvidia/label/cuda-12.4.0

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

pip install -U "jax[cuda12]"

conda install scvi-tools -c conda-forge

module load python
source activate /project/zemmour/david/envs/scvi120_test3

```

failed
```{bash}
module load python/anaconda-2022.05 
conda create -p /project/zemmour/david/envs/scvi120_test2 python=3.10
source activate /project/zemmour/david/envs/scvi120_test2
module load cuda/11.8

conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
pip install jaxlib==0.3.25+cuda11.cudnn82 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html


conda install scvi-tools -c conda-forge

sinteractive --time=0:10:00 --account=pi-zemmour --partition=beagle3 --gres=gpu:1 --mem=8GB
module load python/anaconda-2022.05
module load cuda/11.8
source activate /project/zemmour/david/envs/scvi120_test2
#on midway3-0283 GPU
#import torch
#torch.cuda.is_available()
#True
#torch.cuda.device_count()
#1
#torch.cuda.current_device()
#0
#torch.cuda.device(0)
#<torch.cuda.device object at 0x7f4d19f42af0>
#torch.cuda.get_device_name(0)
#'Quadro RTX 6000'

```

scvi120_test1: failed: jax error this time
```{bash}
module load python/anaconda-2022.05 
conda create -p /project/zemmour/david/envs/scvi120_test1 python=3.10
source activate /project/zemmour/david/envs/scvi120_test1
module load cuda/11.8

conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
pip install -U jax #didn't work

conda install scvi-tools -c conda-forge
#conda install jax jaxlib -c conda-forge didn't 

sinteractive --time=0:10:00 --account=pi-zemmour --partition=beagle3 --gres=gpu:1 --mem=8GB
module load python/anaconda-2022.05
module load cuda/11.8
source activate /project/zemmour/david/envs/scvi120_test1
#on midway3-0283 GPU
#import torch
#torch.cuda.is_available()
#True
#torch.cuda.device_count()
#1
#torch.cuda.current_device()
#0
#torch.cuda.device(0)
#<torch.cuda.device object at 0x7f4d19f42af0>
#torch.cuda.get_device_name(0)
#'Quadro RTX 6000'

```


failed
```{bash}
module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13 

source activate mamba-env  
mamba create -p /project/zemmour/david/envs/scvi120 python=3.10
#log out and log back in to activate the new environment
source activate /project/zemmour/david/envs/scvi120
module load cuda/11.8

mamba install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
mamba install jax jaxlib -c conda-forge

#check installation and GPU works:
sinteractive --time=0:10:00 --account=pi-zemmour --partition=beagle3 --gres=gpu:1 --mem=8GB

module load python/anaconda-2022.05
source activate /project/zemmour/david/envs/scvi120
#on midway3-0283 GPU
#import torch
#torch.cuda.is_available()
#True
#torch.cuda.device_count()
#1
#torch.cuda.current_device()
#0
#torch.cuda.device(0)
#<torch.cuda.device object at 0x7f4d19f42af0>
#torch.cuda.get_device_name(0)
#'Quadro RTX 6000'


conda remove --prefix /project/zemmour/david/envs/scvi120 --all


```

failed
torch installed but not after installing scvi-tools!
```{bash}

module load python/anaconda-2022.05 
conda create -p /project/zemmour/david/envs/scvi120_20241003 python=3.10

source activate /project/zemmour/david/envs/scvi120_20241003

pip3 install torch torchvision

#sinteractive --time=0:10:00 --account=pi-zemmour --partition=beagle3 --gres=gpu:1 --mem=8GB
#source activate /project/zemmour/david/envs/scvi120_20241003
#python
#import torch
#torch.cuda.is_available()
#True

conda install jax jaxlib -c conda-forge
conda install scvi-tools -c conda-forge

module load python/anaconda-2022.05 
source activate /project/zemmour/david/envs/scvi120_20241003
#python
#import torch
#torch.cuda.is_available()
#False

```

