---
title: "DGE_limma_CD4.Rmd"
output: html_document
date: "2024-12-13"
editor_options: 
  chunk_output_type: console
---

**Start interactive session on Midway3**
```{bash}
ssh -Y zemmour@midway3.rcc.uchicago.edu
sinfo -s
#screen -S 0429
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=jfkfloor2 --qos=jfkfloor2 --nodes=1 
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=zemmour-hm --qos=zemmour --nodes=1 
sinteractive --time=12:00:00 --account=pi-zemmour --partition=caslake --nodes=1
sinteractive --time=12:00:00 --account=pi-zemmour --partition=gpu --gres=gpu:1 --mem=64GB
cd $LABHOME

module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13

#source activate /project/jfkfloor2/zemmourlab/david/envs/scvi
source activate /project/zemmour/david/envs/scvi_20240315
module load openblas/0.3.13

cd /project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/CD8AB

R

```

**Initialize: load libraries and custom functions**

```{r}
options(max.print=1000)
setwd("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/CD4")
source("/project/jfkfloor2/zemmourlab/david/immgent/immgent_integration_git/custom_functions_david.R")

libs = c("limma", "edgeR", "Seurat","BPCells", "ggplot2", "dplyr", "rlang","reshape2", "ggrastr", "RColorBrewer", "pals", "scales", "pheatmap") 
#libs = c("matrixStats", "gplots","ggplot2", "reshape2", "scales", "gridExtra", "dplyr", "RColorBrewer", "grid", "Rtsne", "limma",   "RColorBrewer", "pheatmap", "Seurat",  "ggrastr", "ggbeeswarm") #pwr, preprocessCore, "readxl", vegan", "genefilter" "scde" "cellrangerRkit", "Rsamtools", "GenomicRanges", "GenomicAlignments", "VGAM", "WGCNA",rafalib, ‘UsingR’,MAST "ggrastr",
sapply(libs, function(x) suppressMessages(suppressWarnings(library(x, character.only = TRUE, quietly = T, warn.conflicts  = F))))

#options(Seurat.object.assay.version = 'v5')

#Gradients
library(RColorBrewer)
ColorRamp = rev(colorRampPalette(brewer.pal(n = 7,name = "RdYlBu"))(100))
ColorRamp = rev(colorRampPalette(c('red','white','blue'))(20))
ColorRamp = rev(rainbow(10, end = 4/6))
library(viridis)
ColorRamp = rev(viridis(100))
ColorRamp = rev(cividis(100))
#image(1:100, 1, as.matrix(1:100), col = ColorRamp, main = "Color Palette", xaxt = 'n', yaxt = 'n', xlab = "", ylab = "")

#mycol = c("black","blue","red","darkgreen", "orange","purple", "cyan", "greenyellow",    "salmon", "magenta","pink", "tan", "brown") # c("magenta", "red",  "darkgreen", "cyan", "blue", "blue", "blue", "black", "blue", "blue", "blue", "blue", "orange")

#Large Color palette
library("pals")
n = 70
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
mypal1 = unique(unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals))))
mypal1 = mypal1[-4]
mypal = c(glasbey(), polychrome(), mypal1)
names(mypal) = NULL
#pal.bands(mypal, main="Colormap suggestions")

#parade = function(n) { return(Seurat::DiscretePalette(n, palette = "parade", shuffle = F)) }


#pdf("mypal.pdf", 10, 10)
#pie(rep(1,n), col=unique(unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))) )
#pie(rep(1,n), col=unique(unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))), labels =  unique(unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))))
#dev.off()

```

sbatch $SCRIPT_DIR/limma_wrapper_20241217_CD8AB.sh
one vs all
one vs all in resting
one vs all in activated
activated vs resting
```{bash}

```

Make table and signatures (now in each contrast script too)
```{r}
setwd("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/CD8AB/DGE_limma/20241217")

file_list = list.files(pattern = "^ttlist.*\\.Rds$")
for (i in 1:length(file_list)) {
    print(file_list[i])
    dir = gsub(pattern = "ttlist_|\\.Rds", replacement = "", x = file_list[i])
    
    
    #make big table
    tt_list = readRDS(file_list[i])
    if (length(tt_list) > 1) {
        tt = CollapseDiff_limmatrend(tt_list)
    } else {
        tt = tt_list[[1]]
    }
    tt$SYMBOL = rownames(tt)
    colnames(tt) = gsub(pattern = "AveExpr", replacement = "log2AveExpr", colnames(tt))
    colnames(tt) = gsub(pattern = "logFC", replacement = "log2FC", colnames(tt))
    tt = data.frame(SYMBOL = tt$SYMBOL, tt[,!colnames(tt) %in% "SYMBOL"])
    # tt = tt %>% arrange(desc(log2FC)) %>% select(SYMBOL,log2FC, P.Value,adj.P.Val,log2AveExpr)
    write.table(x = tt, file = gsub(pattern = "Rds", replacement = "txt", x = file_list[i]), sep = "\t", quote = F, row.names = F)
    
    output_dir = "."
    prefix_file_name =  gsub(pattern = "ttlist_|\\.Rds", replacement = "", x = file_list[i])
    message("Saving signature abs(log2FC) > 1 & BH adj.P.Val < 0.05")
    
    # Create the directory if it does not exist
        sig_dir = sprintf("%s/%s", output_dir, prefix_file_name)
    if (!dir.exists(sig_dir)) {
        dir.create(sig_dir, recursive = TRUE)
        message("Directory created: ", sig_dir)
    } else {
        message("Directory already exists: ", sig_dir)
    }
    
    # Loop through the list and apply filters, with error handling
    for (j in seq_along(tt_list)) {
        tryCatch({
            print(names(tt_list)[j])
            tt = tt_list[[j]]
            
            # Update column names
            colnames(tt) = gsub(pattern = "AveExpr", replacement = "log2AveExpr", colnames(tt))
            colnames(tt) = gsub(pattern = "logFC", replacement = "log2FC", colnames(tt))
            
            # Filter for upregulated genes and save
            tt %>% 
                filter(log2FC > 0.5 & adj.P.Val < 0.05) %>% 
                arrange(desc(log2FC)) %>% 
                select(SYMBOL, log2FC, log2AveExpr, P.Value, adj.P.Val) %>% 
                write.table(file = sprintf("%s/%s_up.txt", sig_dir, names(tt_list)[j]), sep = "\t", quote = FALSE, row.names = F)
            
            # Filter for downregulated genes and save
            tt %>% 
                filter(log2FC < -0.5 & adj.P.Val < 0.05) %>% 
                arrange(log2FC) %>% 
                select(SYMBOL, log2FC, log2AveExpr, P.Value, adj.P.Val) %>% 
                write.table(file = sprintf("%s/%s_down.txt", sig_dir, names(tt_list)[j]), sep = "\t", quote = FALSE, row.names = F)
        }, error = function(e) {
            message("Error processing: ", names(tt_list)[j], " - ", e$message)
        })
    }
    
    
}


```
