---
title: "MDEs_ForEachDataset"
output: html_document
date: "2025-05-21"
editor_options: 
  chunk_output_type: console
---

**Start interactive session on Midway3**
```{bash}
ssh -Y zemmour@midway3.rcc.uchicago.edu
sinfo -s
screen -S david
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=jfkfloor2 --qos=jfkfloor2 --nodes=1 
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=zemmour-hm --qos=zemmour --nodes=1 
sinteractive --time=12:00:00 --account=pi-zemmour --partition=beagle3-bigmem --nodes=1 --mem=128GB
sinteractive --time=12:00:00 --account=pi-zemmour --partition=caslake --nodes=1 --mem=96GB
sinteractive --time=3:00:00 --account=pi-zemmour --partition=gpu --gres=gpu:1 --mem=152GB
cd $LABHOME

module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13

#sinteractive --time=1:00:00 -p gpu --gres=gpu:1 --account=pi-zemmour 

#source activate /project/jfkfloor2/zemmourlab/david/envs/scvi
source activate /project/zemmour/david/envs/scvi_20240315
module load openblas/0.3.13 #load again or error

cd /project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/
#cd ~/google_drive/ImmgenT/analysis/data_integration/IGT1_56/Treg

#srun --pty --jobid 21908677 -w midway3-0291 /bin/bash

R
#options(max.print=1000)
#options(Seurat.object.assay.version = 'v5')
```

**Initialize in R: load libraries and custom functions**

```{r}
options(max.print=1000)
# setwd("/project/jfkfloor2/zemmourlab/david/immgent/analysis/integration/IGT1_96")
source("/project/jfkfloor2/zemmourlab/david/immgent/immgent_integration_git/custom_functions_david.R")

libs = c("gridExtra","fgsea","fastTopics", "flashier", "Matrix", "Seurat","BPCells", "ggplot2", "dplyr", "reshape2", "ggrastr", "RColorBrewer", "pals", "scales", "pheatmap", "rafalib", "limma") 
#libs = c("m,atrixStats", "gplots","ggplot2", "reshape2", "scales", "gridExtra", "dplyr", "RColorBrewer", "grid", "Rtsne", "limma",   "RColorBrewer", "pheatmap", "Seurat",  "ggrastr", "ggbeeswarm") #pwr, preprocessCore, "readxl", vegan", "genefilter" "scde" "cellrangerRkit", "Rsamtools", "GenomicRanges", "GenomicAlignments", "VGAM", "WGCNA",rafalib, ‘UsingR’,MAST "ggrastr",
sapply(libs, function(x) suppressMessages(suppressWarnings(library(x, character.only = TRUE, quietly = T, warn.conflicts  = F))))


#Gradients
library(RColorBrewer)
ColorRamp = rev(colorRampPalette(brewer.pal(n = 7,name = "RdYlBu"))(100))
# ColorRamp = rev(colorRampPalette(c('red','white','blue'))(20))
ColorRamp = rev(rainbow(10, end = 4/6))
library(viridis)
ColorRamp = rev(viridis(100))
ColorRamp = rev(cividis(100))
ColorRamp = rev(colorRampPalette(c('red','white','blue'))(20))
ColorRamp = colorRampPalette(c('white','red'))(20)
ColorRamp = rev(colorRampPalette(brewer.pal(n = 7,name = "RdBu"))(100))
# ColorRamp = colorRampPalette(c('Red'))(20)
#image(1:100, 1, as.matrix(1:100), col = ColorRamp, main = "Color Palette", xaxt = 'n', yaxt = 'n', xlab = "", ylab = "")

#mycol = c("black","blue","red","darkgreen", "orange","purple", "cyan", "greenyellow",    "salmon", "magenta","pink", "tan", "brown") # c("magenta", "red",  "darkgreen", "cyan", "blue", "blue", "blue", "black", "blue", "blue", "blue", "blue", "orange")

#Large Color palette
library("pals")
n = 70
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
mypal1 = unique(unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals))))
mypal1 = mypal1[-4]
mypal = c(glasbey(), polychrome(), mypal1)
names(mypal) = NULL
#pal.bands(mypal, main="Colormap suggestions")
mypal_organ = setNames(mypal, unique(so$organ_simplified))
mypal_organ = mypal_organ[!is.na(names(mypal_organ))]
mypal_level1 = setNames(mypal, unique(so$annotation_level1))
mypal_level1 = mypal_level1[!is.na(names(mypal_level1))]
mypal_level2 = setNames(mypal, unique(so_orig$annotation_level2))
mypal_level2 = mypal_level2[!is.na(names(mypal_level2))]
mypal_level2["CD4_cl18"] = "blue"
mypal_igt = setNames(mypal, unique(so$IGT))
mypal_igt = mypal_igt[!is.na(names(mypal_igt))]


#parade = function(n) { return(Seurat::DiscretePalette(n, palette = "parade", shuffle = F)) }
```

sbatch $SCRIPT_DIR/mde_plots_wrapper.sh
mde_plots_per_sample.R
```{r}
```



**Load dataset**

```{r}
so_orig = readRDS("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/igt1_96_withtotalvi20250513_clean.Rds") 

```

```{r}

library(gridExtra)

so_orig$is_agspe = !is.na(so_orig$Ag_spe)

so = list()
so[["CD4"]] = so_orig[,so_orig$annotation_level1 == "CD4"]
so[["CD8"]] =  so_orig[,so_orig$annotation_level1 == "CD8"]
so[["Treg"]] =  so_orig[,so_orig$annotation_level1 == "Treg"]
so[["gdT"]] = so_orig[,so_orig$annotation_level1 == "gdT"]
so[["CD8aa"]] = so_orig[,so_orig$annotation_level1 == "CD8aa"]
so[["nonconv"]] = so_orig[,so_orig$annotation_level1 == "nonconv"]
so[["DN"]] = so_orig[,so_orig$annotation_level1 == "DN"]
so[["DP"]] = so_orig[,so_orig$annotation_level1 == "DP"]


i = "IGT37"
level1 = c("CD4", "CD8", "Treg", "gdT", "CD8aa", "nonconv", "DN", "DP")

pdf("MDE_InEachSample/IGT1-96_MDEs.pdf", width = 20, height = 20, useDingbats = F)
for (i in unique(so_orig$IGT)) {
    samples = so_orig@meta.data %>% filter(IGT == i) %>% pull(sample_code) %>% unique()
    for (s in samples) {
        print(s)
        ensure_directory(sprintf("MDE_InEachSample/%s/", i))
        # pdf(sprintf("MDE_InEachSample/%s/%s_MDEs.pdf", i, s), width = 20, height = 20, useDingbats = F)
        ps2 = list()
        ps3 = list()
        p = MyDimPlotHighlight(seurat_object = so_orig, umap_to_plot = "mde2_totalvi_20241006", cells_to_highlight = colnames(so_orig)[which(so_orig$sample_code == s)], highlight_column_name = "annotation_level2", pixels = c(512, 512), mycols = mypal_level2, title = sprintf("%s",s), highlight_size = 1, highlight_alpha = 1, print_plot1 = T, print_plot2 = T, labelclusters = T)
        ps2[["all"]] =  p$plot2
        ps3[["all"]] =  p$plot3
        for (l in level1) {
            # print(l)
            p = MyDimPlotHighlight(seurat_object = so[[l]], umap_to_plot = "mde_incremental", cells_to_highlight = colnames(so[[l]])[which(so[[l]]$sample_code == s)], highlight_column_name = "annotation_level2", pixels = c(512, 512), mycols = mypal_level2, title = sprintf("%s in %s", l, s), highlight_size = 1, highlight_alpha = 1, print_plot1 = T, print_plot2 = T, labelclusters = T)
            ps2[[l]] = p$plot2
            ps3[[l]] = p$plot3 #to get plot with labels
        }
        grid.arrange(grobs = ps3, ncol = 3, nrow = 3)
        # grid.arrange(grobs = ps2, ncol = 3, nrow = 3)
        # dev.off()
    }
}
dev.off()



for (i in unique(so_orig$IGT)) {
    samples = so_orig@meta.data %>% filter(IGT == i) %>% pull(sample_code) %>% unique()
    for (s in samples) {
        print(s)
        ensure_directory(sprintf("MDE_InEachSample/%s/", i))
        pdf(sprintf("MDE_InEachSample/%s/%s_MDEs.pdf", i, s), width = 20, height = 20, useDingbats = F)
        ps2 = list()
        ps3 = list()
        p = MyDimPlotHighlight(seurat_object = so_orig, umap_to_plot = "mde2_totalvi_20241006", cells_to_highlight = colnames(so_orig)[which(so_orig$sample_code == s)], highlight_column_name = "annotation_level2", pixels = c(512, 512), mycols = mypal_level2, title = sprintf("%s",s), highlight_size = 1, highlight_alpha = 1, print_plot1 = T, print_plot2 = T, labelclusters = T)
        ps2[["all"]] =  p$plot2
        ps3[["all"]] =  p$plot3
        for (l in level1) {
            # print(l)
            p = MyDimPlotHighlight(seurat_object = so[[l]], umap_to_plot = "mde_incremental", cells_to_highlight = colnames(so[[l]])[which(so[[l]]$sample_code == s)], highlight_column_name = "annotation_level2", pixels = c(512, 512), mycols = mypal_level2, title = sprintf("%s in %s", l, s), highlight_size = 1, highlight_alpha = 1, print_plot1 = T, print_plot2 = T, labelclusters = T)
            ps2[[l]] = p$plot2
            ps3[[l]] = p$plot3 #to get plot with labels
        }
        grid.arrange(grobs = ps3, ncol = 3, nrow = 3)
        grid.arrange(grobs = ps2, ncol = 3, nrow = 3)
        dev.off()
    }
}








```


For Ag-specific cells only

```{r}
library(gridExtra)

so_orig$is_agspe = !is.na(so_orig$Ag_spe)

so = list()
so[["CD4"]] = so_orig[,so_orig$annotation_level1 == "CD4"]
so[["CD8"]] =  so_orig[,so_orig$annotation_level1 == "CD8"]
so[["Treg"]] =  so_orig[,so_orig$annotation_level1 == "Treg"]
so[["gdT"]] = so_orig[,so_orig$annotation_level1 == "gdT"]
so[["CD8aa"]] = so_orig[,so_orig$annotation_level1 == "CD8aa"]
so[["nonconv"]] = so_orig[,so_orig$annotation_level1 == "nonconv"]
so[["DN"]] = so_orig[,so_orig$annotation_level1 == "DN"]
so[["DP"]] = so_orig[,so_orig$annotation_level1 == "DP"]


# i = "IGT37"
level1 = c("CD4", "CD8", "Treg", "gdT", "CD8aa", "nonconv", "DN", "DP")

igts = so_orig@meta.data %>% filter(is_agspe == T) %>% pull(IGT) %>% unique()

pdf("MDE_InEachSample/IGT1-96_MDEs_AgSpe.pdf", width = 20, height = 20, useDingbats = F)
for (i in igts) {
    samples = so_orig@meta.data %>% filter(IGT == i) %>% pull(sample_code) %>% unique()
    for (s in samples) {
        print(s)
        ensure_directory(sprintf("MDE_InEachSample/%s/", i))
        # pdf(sprintf("MDE_InEachSample/%s/%s_MDEs_AgSpe.pdf", i, s), width = 20, height = 20, useDingbats = F)
        ps2 = list()
        ps3 = list()
        for (l in level1) {
            # print(l)
            p = MyDimPlotHighlight(seurat_object = so[[l]], umap_to_plot = "mde_incremental", cells_to_highlight = colnames(so[[l]])[which(so[[l]]$sample_code == s)], highlight_column_name = "is_agspe", pixels = c(512, 512), mycols = c("black", "red"), title = sprintf("%s in %s", l, s), highlight_size = 1, highlight_alpha = 1, print_plot1 = T, print_plot2 = T, labelclusters = T)
            ps2[[l]] = p$plot2
            ps3[[l]] = p$plot3 #to get plot with labels
        }
        grid.arrange(grobs = ps3, ncol = 3, nrow = 3)
        grid.arrange(grobs = ps2, ncol = 3, nrow = 3)
        # dev.off()
    }
}
dev.off()

pdf("MDE_InEachSample/IGT1-96_MDEs_AgSpe2.pdf", width = 20, height = 20, useDingbats = F)
ps2 = list()
ps3 = list()
for (l in level1) {
    print(l)
    p = MyDimPlotHighlight(seurat_object = so[[l]], umap_to_plot = "mde_incremental", cells_to_highlight = colnames(so[[l]])[which(so[[l]]$is_agspe == T)], highlight_column_name = "Ag_spe", pixels = c(512, 512), mycols = mypal, title = sprintf("Ag spe in %s", l), highlight_size = 1, highlight_alpha = 1, print_plot1 = T, print_plot2 = T, labelclusters = T)
    ps2[[l]] = p$plot2
    ps3[[l]] = p$plot3 #to get plot with labels
}
grid.arrange(grobs = ps3, ncol = 3, nrow = 3)
grid.arrange(grobs = ps2, ncol = 3, nrow = 3)
dev.off()

```


**Export images for movie**
```{r}

dir.create("MDE_InEachSample/frames_all")

samples = so_orig@meta.data %>% pull(sample_code) %>% unique()
l = "all"

for (i in 1:length(samples)) {
    print(samples[i])
    p = MyDimPlotHighlight(seurat_object = so_orig, umap_to_plot = "mde2_totalvi_20241006", cells_to_highlight = colnames(so_orig)[which(so_orig$sample_code == samples[i])], highlight_column_name = "annotation_level2", pixels = c(512, 512), mycols = mypal_level2, title = sprintf("%s",samples[i]), highlight_size = 1, highlight_alpha = 1, print_plot1 = T, print_plot2 = T, labelclusters = T)
    # p = MyDimPlotHighlight(seurat_object = so[[l]], umap_to_plot = "mde_incremental", cells_to_highlight = colnames(so[[l]])[which(so[[l]]$sample_code == s)], highlight_column_name = "annotation_level2", pixels = c(512, 512), mycols = mypal_level2, title = sprintf("%s in %s", l, s), highlight_size = 1, highlight_alpha = 1, print_plot1 = T, print_plot2 = T, labelclusters = T)
    ggsave(sprintf("MDE_InEachSample/frames_all/frame_%03d.png", i), plot = p$plot2, width = 5, height = 5, bg = "white")
}



```

```{r}
##On my desktop (couldn't install av on midway3)
library(av)
setwd('/Users/david/Library/CloudStorage/GoogleDrive-zemmour@uchicago.edu/My Drive/ImmgenT/analysis/data_integration/IGT1_96/MDE_InEachSample')

# Create a video from the PNG frames
av_encode_video(
  list.files("frames_all", full.names = TRUE), 
  framerate = 10,           # 10 frames per second
  output = "immgenT_movie_all.mp4"
)

```















