---
title: "FlashierDGE"
output: html_document
date: "2025-04-24"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
options(max.print=1000)
setwd("/Users/david/google_drive_uchicago/ImmgenT/analysis/data_integration/IGT1_96/topic/flashier20250215_alldata_backfit/")
source("/Users/david/google_drive/ImmgenT/analysis/immgent_integration_git/custom_functions_david.R")

libs = c("ggplot2", "dplyr", "reshape2", "RColorBrewer", "pals", "viridis") 
sapply(libs, function(x) suppressMessages(suppressWarnings(library(x, character.only = TRUE, quietly = T, warn.conflicts  = F))))


#Gradients
library(RColorBrewer)
ColorRamp = rev(colorRampPalette(brewer.pal(n = 7,name = "RdYlBu"))(100))
# ColorRamp = rev(colorRampPalette(c('red','white','blue'))(20))
ColorRamp = rev(rainbow(10, end = 4/6))
library(viridis)
ColorRamp = rev(viridis(100))
ColorRamp = rev(cividis(100))
ColorRamp = rev(colorRampPalette(c('red','white','blue'))(20))
ColorRamp = colorRampPalette(c('white','red'))(20)
ColorRamp = rev(colorRampPalette(brewer.pal(n = 7,name = "RdBu"))(100))
# ColorRamp = colorRampPalette(c('Red'))(20)
#image(1:100, 1, as.matrix(1:100), col = ColorRamp, main = "Color Palette", xaxt = 'n', yaxt = 'n', xlab = "", ylab = "")

#mycol = c("black","blue","red","darkgreen", "orange","purple", "cyan", "greenyellow",    "salmon", "magenta","pink", "tan", "brown") # c("magenta", "red",  "darkgreen", "cyan", "blue", "blue", "blue", "black", "blue", "blue", "blue", "blue", "orange")

#Large Color palette
# library("pals")
# n = 70
# qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
# mypal1 = unique(unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals))))
# mypal1 = mypal1[-4]
# mypal = c(glasbey(), polychrome(), mypal1)
# names(mypal) = NULL
# #pal.bands(mypal, main="Colormap suggestions")
# mypal_organ = setNames(mypal, unique(so$organ_simplified))
# mypal_organ = mypal_organ[!is.na(names(mypal_organ))]
# mypal_level1 = setNames(mypal, unique(so$annotation_level1))
# mypal_level1 = mypal_level1[!is.na(names(mypal_level1))]
# mypal_igt = setNames(mypal, unique(so$IGT))
# mypal_igt = mypal_igt[!is.na(names(mypal_igt))]



```

Custom functions
```{r}
TopicDGEPlots = function(F1, L1, group1, group2, mdata_orig, title_plot = "") {
    
    require(ggplot2)
    require(ggrepel)
    require(dplyr)
    require(scattermore)
    
    # Calculate the loadings
    loadings_group1 = colMeans(L1[group1,])
    loadings_group2 = colMeans(L1[group2,])
    loadings_groups = colMeans(L1[c(group1, group2),])
    
    # Mean genes for each group
    mean_genes_group1 = F1 %*% loadings_group1
    mean_genes_group2 = F1 %*% loadings_group2
    mean_genes = F1 %*% colMeans(L1[c(group1, group2),])
    
    # Fold Change between the two groups
    fc_loadings = loadings_group1 - loadings_group2
    fc_genes = F1 %*% fc_loadings %>% as.data.frame()  # take exp to have the actual FC
    
    # Create vplot for fold changes (MA plot of factors)
    vplot = data.frame(SYMBOL = names(fc_loadings), log2FC = fc_loadings / log(2), AveExpr = loadings_groups)
    
    # Maximum FC for symmetrical x-axis range
    max_fc = ceiling(max(abs(vplot$log2FC)))  # Get the max of the absolute FC values and round up
    top_genes = vplot %>%
        arrange(desc(abs(log2FC))) %>%
        head(50)
    
    # MA Plot (Factors)
    p1 = ggplot(data = vplot) + 
        geom_point(aes(x = log2FC, y = AveExpr), colour = "black", alpha = I(1), size = I(1)) +
        xlim(-max_fc, max_fc) +  # Set symmetrical x-axis range
        geom_text_repel(data = top_genes, aes(x = log2FC, y = AveExpr, label = SYMBOL), 
                        size = 3, color = "red", box.padding = 0.35, point.padding = 0.5, segment.color = 'grey50', max.overlaps  = 20) +
        theme_minimal() +
        labs(
            x = "Fold Change (log2)",
            y = "Average Expression",
            title = title_plot
        )
    
    # Create vplot for gene expression (MA plot of genes)
    vplot_genes = data.frame(SYMBOL = rownames(fc_genes), log2FC = fc_genes[,1] / log(2), AveExpr = mean_genes[,1])
    
    # Maximum FC for symmetrical x-axis range (for genes)
    max_fc_genes = ceiling(max(abs(vplot_genes$log2FC)))  # Get the max of the absolute FC values and round up
    top_genes_genes <- vplot_genes %>%
        arrange(desc(abs(log2FC))) %>%
        head(50)
    
    # MA Plot (Genes)
    p2 <- ggplot(data = vplot_genes) + 
        geom_scattermore(aes(x = log2FC, y = AveExpr), colour = "black", alpha = I(1), size = I(1), pixels = c(512, 512)) +
        xlim(-max_fc_genes, max_fc_genes) +  # Set symmetrical x-axis range
        geom_text_repel(data = top_genes_genes, aes(x = log2FC, y = AveExpr, label = SYMBOL), 
                        size = 3, color = "red", box.padding = 0.35, point.padding = 0.5, segment.color = 'grey50', max.overlaps  = 20) +
        theme_minimal() +
        labs(
            x = "Fold Change (log2)",
            y = "Average Expression",
            title = title_plot
        )
    
    # Return the plots and vplot tables
    list(p1 = p1, p2 = p2, diff_factors = vplot, diff_genes = vplot_genes)
}
```


```{r}
F1 = read.table("gene_factor_matrix.txt", header = T, sep = "\t") %>% as.matrix()
L1 = read.table("cell_factor_matrix.txt", header = T, sep = "\t") %>% as.matrix()

library(bigmemory)
mat = read.big.matrix("cell_factor_matrix.txt", header = F, type = "double", sep = "\t")


mdata_orig = read.table("mdata_mde_L1.txt", header = T, sep = "\t")
L1 = mdata_orig[,grep("^F[0-9]+$", colnames(mdata_orig), value = TRUE)]

mdata_orig %>% select(IGT, exp_name) %>% unique()

```

```{r}
group1 = mdata_orig %>% filter(annotation_level1 %in% c("Treg") & annotation_level2 %in% c("Treg_cl8") & organ_simplified == "colon" & condition_broad == "healthy") %>% pull(cellID)
group2 = mdata_orig %>% filter(annotation_level1 %in% c("Treg") & annotation_level2 %in% c("Treg_cl2") & organ_simplified == "colon" & condition_broad == "healthy") %>% pull(cellID)

group1 = mdata_orig %>% filter(annotation_level1 %in% c("Treg") & condition_broad == "healthy") %>% pull(cellID)
group2 = mdata_orig %>% filter( !(annotation_level1 %in% c("Treg")) & condition_broad == "healthy") %>% pull(cellID)

results = TopicDGEPlots(F1, L1, group1, group2, mdata_orig, title_plot = "Treg vs all in healthy")

# results$p1  # First plot (MA plot of factors)
# results$p2  # Second plot (MA plot of genes)
# results$diff_factors  # vplot for fold changes
results$diff_genes %>% arrange(desc(log2FC)) # vplot for gene expression

# Call the function with F1, L1, and group data
results = TopicDGEPlots(F1, L1, group1, group2, mdata_orig, title_plot = "Treg_cl8 vs Treg_cl2 in colon healthy")

# Access the plots and data
results$p1  # First plot (MA plot of factors)
results$p2  # Second plot (MA plot of genes)
results$diff_factors  # vplot for fold changes
results$diff_genes  # vplot for gene expression


```


