---
title: "Treg_misc"
output: html_document
date: "2025-05-28"
author: "David Zemmour"
editor_options: 
  chunk_output_type: console
---

**Initialize: load libraries and custom functions**

```{bash}
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=jfkfloor2 --qos=jfkfloor2 --nodes=1 
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=beagle3-bigmem --nodes=1 
sinteractive --exclusive --time=12:00:00 --account=pi-zemmour --partition=zemmour-hm --qos=zemmour --nodes=1 
sinteractive --time=03:00:00 --account=pi-zemmour --partition=caslake --nodes=1 --mem=96GB

module load python/anaconda-2022.05 
module load hdf5/1.12.0 #for BPCells but also others
module load openblas/0.3.13
source activate /project/zemmour/david/envs/scvi_20240315
#source activate /project/zemmour/david/envs/r443
module load openblas/0.3.13

cd /project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/Treg
R
```


```{r}
# setwd("~/google_drive_uchicago/ImmgenT/analysis/data_integration/IGT1_96")
libs = c("gridExtra","Matrix", "Seurat", "ggplot2", "dplyr", "reshape2", "ggrastr","scattermore", "RColorBrewer", "pals", "scales", "pheatmap", "rafalib") 
sapply(libs, function(x) suppressMessages(suppressWarnings(library(x, character.only = TRUE, quietly = T, warn.conflicts  = F))))
source("/project/jfkfloor2/zemmourlab/david/immgent/immgent_integration_git/custom_functions_david.R")

ColorRamp = rev(colorRampPalette(brewer.pal(n = 7,name = "RdYlBu"))(100))
ColorRamp = rev(colorRampPalette(c('red','white','blue'))(20))
ColorRamp = rev(rainbow(10, end = 4/6))
ColorRamp = rev(viridis(100))
ColorRamp = brewer.pal(9, "Blues")

#mycol = c("black","blue","red","darkgreen", "orange","purple", "cyan", "greenyellow",    "salmon", "magenta","pink", "tan", "brown") # c("magenta", "red",  "darkgreen", "cyan", "blue", "blue", "blue", "black", "blue", "blue", "blue", "blue", "orange")

#Large Color palette
library("pals")
n = 70
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
mypal1 = unique(unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals))))
mypal1 = mypal1[-4]
mypal = c(glasbey(), polychrome(), mypal1)
names(mypal) = NULL
#pal.bands(mypal, main="Colormap suggestions")
mypal_organ = setNames(mypal, unique(so$organ_simplified))
mypal_organ = mypal_organ[!is.na(names(mypal_organ))]
mypal_level1 = setNames(mypal, unique(so$annotation_level1))
mypal_level1 = mypal_level1[!is.na(names(mypal_level1))]
mypal_level2 = setNames(mypal, unique(so_orig$annotation_level2))
mypal_level2 = mypal_level2[!is.na(names(mypal_level2))]
mypal_level2["CD4_cl18"] = "blue"
mypal_igt = setNames(mypal, unique(so$IGT))
mypal_igt = mypal_igt[!is.na(names(mypal_igt))]


```

**Most up-to-date data**
on Midway
```{r}
so_orig = readRDS("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/igt1_96_withtotalvi20250513_clean.Rds") 

so =  so_orig[,so_orig$annotation_level1 == "Treg"]



```

on Desktop
```{bash}
source('/Users/david/Library/CloudStorage/GoogleDrive-david.puyraimond@gmail.com/My Drive/ImmgenT/analysis/immgent_integration_git/custom_functions_david.R')

tt_list = readRDS('/Users/david/Library/CloudStorage/GoogleDrive-zemmour@uchicago.edu/My Drive/ImmgenT/analysis/data_integration/IGT1_96/Treg/DGE_limma/20250109/ttlist_OneVsAll.Rds')

```


**FCFC plots**
```{r}
source('/Users/david/Library/CloudStorage/GoogleDrive-david.puyraimond@gmail.com/My Drive/ImmgenT/analysis/immgent_integration_git/custom_functions_david.R')

tt_list = readRDS('/Users/david/Library/CloudStorage/GoogleDrive-zemmour@uchicago.edu/My Drive/ImmgenT/analysis/data_integration/IGT1_96/Treg/DGE_limma/20250109/ttlist_OneVsAll.Rds')

names(tt_list)


# Create the vplot dataframe with fold changes
vplot = data.frame(fc1 = exp(tt_list$CD8_cl10_vs_All$logFC), fc2 = exp(tt_list$CD8_cl11_vs_All$logFC), SYMBOL = tt_list$CD8_cl10_vs_All$SYMBOL)

# Identify genes with large fold changes (>2)
genes_to_plot = abs(tt_list$CD8_cl10_vs_All$logFC) > 0.69 | abs(tt_list$CD8_cl11_vs_All$logFC) > 0.69
# genes_to_label = vplot[genes_to_plot, ]
genes_to_label = vplot$SYMBOL[genes_to_plot]

# Create the plot
FCFCplot(vplot, 
         xlab = "FC for CD8_cl10", 
         ylab = "FC for CD8_cl11", 
         main = "Fold Change vs Fold Change", 
         genes_to_label = genes_to_label)

FCFCplot(vplot, 
         xlab = "FC for CD8_cl10", 
         ylab = "FC for CD8_cl11", 
         main = "Fold Change vs Fold Change", 
         genes_to_label = NULL)

vplot = data.frame(fc1 = exp(tt_list$CD8_cl10_vs_All$logFC), fc2 = exp(tt_list$CD8_cl7_vs_All$logFC), SYMBOL = tt_list$CD8_cl10_vs_All$SYMBOL)
# Identify genes with large fold changes (>2)
genes_to_plot = abs(tt_list$CD8_cl10_vs_All$logFC) > 0.69 | abs(tt_list$CD8_cl7_vs_All$logFC) > 0.69
genes_to_label = vplot[genes_to_plot, ]
# Create the plot
FCFCplot(vplot, 
         xlab = "FC for CD8_cl10", 
         ylab = "FC for CD8_cl7", 
         main = "Fold Change vs Fold Change", 
         printgeomtext = T, 
         genes_to_label = genes_to_label)



```

**MDE plots**
```{r}


o = unique(so$organ_simplified)

pdf("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/Treg/MDE_organs_20250528.pdf", width = 10, height = 10, useDingbats = F)
for (o in unique(so$organ_simplified)) {
    print(o)
    p = MyDimPlotHighlight(seurat_object = so[,so$condition_broad == "healthy"], umap_to_plot = "mde_incremental", cells_to_highlight = colnames(so)[which(so$organ_simplified %in% o)], highlight_column_name = "annotation_level2", pixels = c(512, 512), mycols = mypal_level2, title = o, highlight_size = 0.5, highlight_alpha = 0.5, print_plot1 = T, print_plot2 = T, labelclusters = T)
    print(p)
}

dev.off()


pdf("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/Treg/MDE_organs_20250528.pdf", width = 10, height = 20, useDingbats = F)
# p = DimPlot(so[,so$condition_broad == "healthy"], reduction = "mde_incremental", group.by = "annotation_level2", split.by = "organ_simplified", raster = F, raster.dpi = c(512,512), label = F, pt.size = 0.5, ncol = 3) + scale_color_manual(values = mypal_level2)
# p + NoLegend()
p = DimPlot(so, reduction = "mde_incremental", group.by = "annotation_level2", split.by = "organ_simplified", raster = F, raster.dpi = c(512,512), label = F, pt.size = 0.2, ncol = 3) + scale_color_manual(values = mypal_level2)
p + NoLegend()
dev.off()

```

**Feature plots**
```{r}
so = so[,so$cite_seq]
so = NormalizeData(so,assay = "RNA", normalization.method = "LogNormalize",verbose = T)
so = NormalizeData(so,assay = "ADT", normalization.method = "LogNormalize",verbose = T)

pdf("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/Treg/MDE_CD62L_20250528.pdf", width = 7, height = 7, useDingbats = F)
FeaturePlot(so, reduction = "mde_incremental", slot = "data", features = "CD62L", order = T, raster = F, raster.dpi = c(512,512))
dev.off()

pdf("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/Treg/MyFeatureScatter_CD62LCD44_20250528.pdf", width = 7, height = 7, useDingbats = F)
for (pop in unique(so$annotation_level2)) {
    print(pop)
    feature1 = "CD62L"
    feature2 = "CD44"
    feature1_th1 = 0
    feature1_th2 = 0
    pop_split = strsplit(pop, split = ",") %>% unlist() #if interested population is a mixture of several clusters
    so@meta.data[,sprintf("is_%s", pop)] = factor(so$annotation_level2 %in% pop_split) #so@meta.data[,sprintf("is_%s", cl)] =
    p = MyFeatureScatter(so,slot = "data",feature1 = feature1, feature2 = feature2, group.by = sprintf("is_%s", pop),split.by = NULL, raster = F) + geom_vline(aes(xintercept = feature1_th1), linetype="dashed", color = "brown") + geom_hline(aes(yintercept = feature1_th2), linetype="dashed", color = "brown") + ggtitle(sprintf("is_%s", pop))
    print(p)
}

dev.off()

pdf("/project/zemmour/david/ImmgenT/analysis/data_integration/IGT1_96/Treg/FeatureScatter_CD62LCD44_20250528.pdf", width = 7, height = 7, useDingbats = F)
FeatureScatter(so[,so$condition_broad == "healthy" & !so$annotation_level2 %in% c("Treg_prolif", "Treg_miniverse")],slot = "data",feature1 = "CD62L",feature2 =  "CD44", group.by = "annotation_level2", raster = F, pt.size = 0.1, split.by =  "annotation_level2", ncol = 3) + scale_color_manual(values = mypal_level2) + NoLegend() #+ geom_vline(aes(xintercept = th1), linetype="dashed", color = "brown") + geom_hline(aes(yintercept = th2), linetype="dashed", color = "brown")
FeatureScatter(so[,so$condition_broad == "healthy" & !so$annotation_level2 %in% c("Treg_prolif", "Treg_miniverse")],slot = "data",feature1 = "CD62L",feature2 =  "CD44", group.by = "annotation_level2", raster = T, pt.size = 0.1) + scale_color_manual(values = mypal_level2) + NoLegend() #+ geom_vline(aes(xintercept = th1), linetype="dashed", color = "brown") + geom_hline(aes(yintercept = 
dev.off()

FeatureScatter(so, slot = "data", features = "CD62L", order = T, raster = T, raster.dpi = c(512,512))

```














